import type { StoreBotState } from "./types";

export const TEST_BUSINESS_ID = "business-double-a-demo";
export const TEST_CUSTOMER_PHONE = "+96170000000";

export const seedStoreBotState: StoreBotState = {
  businesses: [
    {
      id: TEST_BUSINESS_ID,
      name: "Double A Demo Store",
      phone: "+961 70 000 000",
      supportedLanguages: ["en", "ar"],
      defaultLanguage: "en",
    },
  ],
  categories: [
    {
      id: "cat-coffee",
      businessId: TEST_BUSINESS_ID,
      name: "Coffee",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: "cat-bakery",
      businessId: TEST_BUSINESS_ID,
      name: "Bakery",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: "cat-gifts",
      businessId: TEST_BUSINESS_ID,
      name: "Gift Boxes",
      sortOrder: 3,
      isActive: true,
    },
  ],
  products: [
    {
      id: "prod-espresso",
      businessId: TEST_BUSINESS_ID,
      categoryId: "cat-coffee",
      name: "Signature Espresso",
      description: "A compact house blend shot.",
      basePrice: 2.5,
      stockQuantity: 24,
      isActive: true,
    },
    {
      id: "prod-latte",
      businessId: TEST_BUSINESS_ID,
      categoryId: "cat-coffee",
      name: "Velvet Latte",
      description: "Steamed milk with a smooth espresso base.",
      basePrice: 4,
      stockQuantity: 18,
      isActive: true,
    },
    {
      id: "prod-croissant",
      businessId: TEST_BUSINESS_ID,
      categoryId: "cat-bakery",
      name: "Butter Croissant",
      description: "Fresh laminated pastry.",
      basePrice: 3.25,
      stockQuantity: 5,
      isActive: true,
    },
    {
      id: "prod-brownie",
      businessId: TEST_BUSINESS_ID,
      categoryId: "cat-bakery",
      name: "Cocoa Brownie",
      description: "Dense chocolate square.",
      basePrice: 3.75,
      stockQuantity: 0,
      isActive: false,
    },
    {
      id: "prod-mini-box",
      businessId: TEST_BUSINESS_ID,
      categoryId: "cat-gifts",
      name: "Mini Treat Box",
      description: "A small mixed sweets box.",
      basePrice: 14,
      stockQuantity: 7,
      isActive: true,
    },
    {
      id: "prod-family-box",
      businessId: TEST_BUSINESS_ID,
      categoryId: "cat-gifts",
      name: "Family Celebration Box",
      description: "A larger sharing box for gatherings.",
      basePrice: 28,
      stockQuantity: 3,
      isActive: true,
    },
  ],
  variants: [
    {
      id: "var-latte-small",
      businessId: TEST_BUSINESS_ID,
      productId: "prod-latte",
      variantType: "Size",
      name: "Small",
      priceDelta: 0,
      stockQuantity: 10,
      isActive: true,
    },
    {
      id: "var-latte-large",
      businessId: TEST_BUSINESS_ID,
      productId: "prod-latte",
      variantType: "Size",
      name: "Large",
      priceDelta: 1,
      stockQuantity: 8,
      isActive: true,
    },
    {
      id: "var-box-classic",
      businessId: TEST_BUSINESS_ID,
      productId: "prod-family-box",
      variantType: "Theme",
      name: "Classic",
      priceDelta: 0,
      stockQuantity: 2,
      isActive: true,
    },
    {
      id: "var-box-premium",
      businessId: TEST_BUSINESS_ID,
      productId: "prod-family-box",
      variantType: "Theme",
      name: "Premium",
      priceDelta: 8,
      stockQuantity: 1,
      isActive: true,
    },
  ],
  orders: [],
  sessions: [],
};
