/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SpreadsheetRouteImport } from './routes/spreadsheet'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LogsWABotRouteImport } from './routes/logsWABot'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as Dashboard2RouteImport } from './routes/dashboard-2'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as Dashboard2IndexRouteImport } from './routes/dashboard-2.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkUno400RouteImport } from './routes/work/uno400'
import { Route as WorkTijaratiProRouteImport } from './routes/work/tijarati-pro'
import { Route as WorkSnapgoRouteImport } from './routes/work/snapgo'
import { Route as WorkKoubarGroupRouteImport } from './routes/work/koubar-group'
import { Route as WorkDetailingLabRouteImport } from './routes/work/detailing-lab'
import { Route as WorkDataInsightsRouteImport } from './routes/work/data-insights'
import { Route as StoresPavoneRouteImport } from './routes/stores/pavone'
import { Route as QuotationsKhadamatiRouteImport } from './routes/quotations.khadamati'
import { Route as MenusMarleysRouteImport } from './routes/menus/marleys'
import { Route as DashboardSimulatorRouteImport } from './routes/dashboard.simulator'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardDeliveryRouteImport } from './routes/dashboard.delivery'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as Dashboard2SimulatorRouteImport } from './routes/dashboard-2.simulator'
import { Route as Dashboard2SettingsRouteImport } from './routes/dashboard-2.settings'
import { Route as Dashboard2ProductsRouteImport } from './routes/dashboard-2.products'
import { Route as Dashboard2OrdersRouteImport } from './routes/dashboard-2.orders'
import { Route as Dashboard2DeliveryRouteImport } from './routes/dashboard-2.delivery'
import { Route as Dashboard2CategoriesRouteImport } from './routes/dashboard-2.categories'
import { Route as AdminWhatsappTemplatesRouteImport } from './routes/admin.whatsapp-templates'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminFlowTemplatesRouteImport } from './routes/admin.flow-templates'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminAppReviewDemoRouteImport } from './routes/admin.app-review-demo'
import { Route as StoresPavoneIndexRouteImport } from './routes/stores/pavone.index'
import { Route as StoresPavoneWishlistRouteImport } from './routes/stores/pavone.wishlist'
import { Route as StoresPavoneShopRouteImport } from './routes/stores/pavone.shop'
import { Route as StoresPavoneAdminRouteImport } from './routes/stores/pavone.admin'
import { Route as DashboardOrdersOrderIdRouteImport } from './routes/dashboard.orders.$orderId'
import { Route as Dashboard2OrdersOrderIdRouteImport } from './routes/dashboard-2.orders.$orderId'
import { Route as ApiWhatsappWebhook2RouteImport } from './routes/api.whatsapp.webhook-2'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as ApiWaDashboardUploadRouteImport } from './routes/api.wa-dashboard.upload'
import { Route as ApiWaDashboardSessionRouteImport } from './routes/api.wa-dashboard.session'
import { Route as ApiWaDashboardOrdersRouteImport } from './routes/api.wa-dashboard.orders'
import { Route as ApiWaDashboardNotificationsRouteImport } from './routes/api.wa-dashboard.notifications'
import { Route as ApiWaDashboardLogoutRouteImport } from './routes/api.wa-dashboard.logout'
import { Route as ApiWaDashboardLoginRouteImport } from './routes/api.wa-dashboard.login'
import { Route as ApiWaDashboardDiagnosticsRouteImport } from './routes/api.wa-dashboard.diagnostics'
import { Route as ApiWaDashboardCatalogRouteImport } from './routes/api.wa-dashboard.catalog'
import { Route as ApiWaDashboard2UploadRouteImport } from './routes/api.wa-dashboard-2.upload'
import { Route as ApiWaDashboard2SessionRouteImport } from './routes/api.wa-dashboard-2.session'
import { Route as ApiWaDashboard2OrdersRouteImport } from './routes/api.wa-dashboard-2.orders'
import { Route as ApiWaDashboard2LogoutRouteImport } from './routes/api.wa-dashboard-2.logout'
import { Route as ApiWaDashboard2LoginRouteImport } from './routes/api.wa-dashboard-2.login'
import { Route as ApiWaDashboard2DiagnosticsRouteImport } from './routes/api.wa-dashboard-2.diagnostics'
import { Route as ApiWaDashboard2CatalogRouteImport } from './routes/api.wa-dashboard-2.catalog'
import { Route as ApiWaAdminWhatsappTemplatesRouteImport } from './routes/api.wa-admin.whatsapp-templates'
import { Route as ApiWaAdminSessionRouteImport } from './routes/api.wa-admin.session'
import { Route as ApiWaAdminSendReviewMessageRouteImport } from './routes/api.wa-admin.send-review-message'
import { Route as ApiWaAdminReviewConnectionsRouteImport } from './routes/api.wa-admin.review-connections'
import { Route as ApiWaAdminOverviewRouteImport } from './routes/api.wa-admin.overview'
import { Route as ApiWaAdminMessageEventsRouteImport } from './routes/api.wa-admin.message-events'
import { Route as ApiWaAdminLogsRouteImport } from './routes/api.wa-admin.logs'
import { Route as ApiWaAdminLogoutRouteImport } from './routes/api.wa-admin.logout'
import { Route as ApiWaAdminLoginRouteImport } from './routes/api.wa-admin.login'
import { Route as ApiWaAdminFlowTemplatesRouteImport } from './routes/api.wa-admin.flow-templates'
import { Route as ApiWaAdminBusinessesRouteImport } from './routes/api.wa-admin.businesses'
import { Route as AdminFlowTemplatesNewRouteImport } from './routes/admin.flow-templates.new'
import { Route as AdminFlowTemplatesTemplateIdRouteImport } from './routes/admin.flow-templates.$templateId'
import { Route as AdminBusinessesNewRouteImport } from './routes/admin.businesses.new'
import { Route as AdminBusinessesBusinessIdRouteImport } from './routes/admin.businesses.$businessId'
import { Route as StoresPavoneAdminIndexRouteImport } from './routes/stores/pavone.admin.index'
import { Route as StoresPavoneProductSlugRouteImport } from './routes/stores/pavone.product.$slug'
import { Route as StoresPavoneCategorySlugRouteImport } from './routes/stores/pavone.category.$slug'
import { Route as StoresPavoneAdminSettingsRouteImport } from './routes/stores/pavone.admin.settings'
import { Route as StoresPavoneAdminProductsRouteImport } from './routes/stores/pavone.admin.products'
import { Route as StoresPavoneAdminOrdersRouteImport } from './routes/stores/pavone.admin.orders'
import { Route as StoresPavoneAdminLoginRouteImport } from './routes/stores/pavone.admin.login'
import { Route as StoresPavoneAdminInspirationsRouteImport } from './routes/stores/pavone.admin.inspirations'
import { Route as StoresPavoneAdminCategoriesRouteImport } from './routes/stores/pavone.admin.categories'
import { Route as ApiWaDashboardOrdersOrderIdRouteImport } from './routes/api.wa-dashboard.orders.$orderId'
import { Route as ApiWaDashboard2OrdersOrderIdRouteImport } from './routes/api.wa-dashboard-2.orders.$orderId'
import { Route as ApiWaAdminFlowTemplatesTemplateIdRouteImport } from './routes/api.wa-admin.flow-templates.$templateId'
import { Route as ApiWaAdminBusinessesBusinessIdRouteImport } from './routes/api.wa-admin.businesses.$businessId'
import { Route as AdminBusinessesBusinessIdProductsRouteImport } from './routes/admin.businesses.$businessId.products'
import { Route as AdminBusinessesBusinessIdFlowBuilderRouteImport } from './routes/admin.businesses.$businessId.flow-builder'
import { Route as AdminBusinessesBusinessIdCategoriesRouteImport } from './routes/admin.businesses.$businessId.categories'
import { Route as AdminBusinessesBusinessIdCatalogRoutesRouteImport } from './routes/admin.businesses.$businessId.catalog-routes'
import { Route as AdminBusinessesBusinessIdCatalogRouteValuesRouteImport } from './routes/admin.businesses.$businessId.catalog-route-values'
import { Route as ApiWaAdminBusinessesBusinessIdFlowRouteImport } from './routes/api.wa-admin.businesses.$businessId.flow'
import { Route as AdminFlowTemplatesTemplateIdVersionsVersionIdRouteImport } from './routes/admin.flow-templates.$templateId.versions.$versionId'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsheetRoute = SpreadsheetRouteImport.update({
  id: '/spreadsheet',
  path: '/spreadsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsWABotRoute = LogsWABotRouteImport.update({
  id: '/logsWABot',
  path: '/logsWABot',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard2Route = Dashboard2RouteImport.update({
  id: '/dashboard-2',
  path: '/dashboard-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const Dashboard2IndexRoute = Dashboard2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Dashboard2Route,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkUno400Route = WorkUno400RouteImport.update({
  id: '/work/uno400',
  path: '/work/uno400',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTijaratiProRoute = WorkTijaratiProRouteImport.update({
  id: '/work/tijarati-pro',
  path: '/work/tijarati-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSnapgoRoute = WorkSnapgoRouteImport.update({
  id: '/work/snapgo',
  path: '/work/snapgo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkKoubarGroupRoute = WorkKoubarGroupRouteImport.update({
  id: '/work/koubar-group',
  path: '/work/koubar-group',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDetailingLabRoute = WorkDetailingLabRouteImport.update({
  id: '/work/detailing-lab',
  path: '/work/detailing-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDataInsightsRoute = WorkDataInsightsRouteImport.update({
  id: '/work/data-insights',
  path: '/work/data-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresPavoneRoute = StoresPavoneRouteImport.update({
  id: '/pavone',
  path: '/pavone',
  getParentRoute: () => StoresRoute,
} as any)
const QuotationsKhadamatiRoute = QuotationsKhadamatiRouteImport.update({
  id: '/quotations/khadamati',
  path: '/quotations/khadamati',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusMarleysRoute = MenusMarleysRouteImport.update({
  id: '/menus/marleys',
  path: '/menus/marleys',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSimulatorRoute = DashboardSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveryRoute = DashboardDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const Dashboard2SimulatorRoute = Dashboard2SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => Dashboard2Route,
} as any)
const Dashboard2SettingsRoute = Dashboard2SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Dashboard2Route,
} as any)
const Dashboard2ProductsRoute = Dashboard2ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => Dashboard2Route,
} as any)
const Dashboard2OrdersRoute = Dashboard2OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => Dashboard2Route,
} as any)
const Dashboard2DeliveryRoute = Dashboard2DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => Dashboard2Route,
} as any)
const Dashboard2CategoriesRoute = Dashboard2CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => Dashboard2Route,
} as any)
const AdminWhatsappTemplatesRoute = AdminWhatsappTemplatesRouteImport.update({
  id: '/whatsapp-templates',
  path: '/whatsapp-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlowTemplatesRoute = AdminFlowTemplatesRouteImport.update({
  id: '/flow-templates',
  path: '/flow-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppReviewDemoRoute = AdminAppReviewDemoRouteImport.update({
  id: '/app-review-demo',
  path: '/app-review-demo',
  getParentRoute: () => AdminRoute,
} as any)
const StoresPavoneIndexRoute = StoresPavoneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneWishlistRoute = StoresPavoneWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneShopRoute = StoresPavoneShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneAdminRoute = StoresPavoneAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const DashboardOrdersOrderIdRoute = DashboardOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const Dashboard2OrdersOrderIdRoute = Dashboard2OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => Dashboard2OrdersRoute,
} as any)
const ApiWhatsappWebhook2Route = ApiWhatsappWebhook2RouteImport.update({
  id: '/api/whatsapp/webhook-2',
  path: '/api/whatsapp/webhook-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboardUploadRoute = ApiWaDashboardUploadRouteImport.update({
  id: '/api/wa-dashboard/upload',
  path: '/api/wa-dashboard/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboardSessionRoute = ApiWaDashboardSessionRouteImport.update({
  id: '/api/wa-dashboard/session',
  path: '/api/wa-dashboard/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboardOrdersRoute = ApiWaDashboardOrdersRouteImport.update({
  id: '/api/wa-dashboard/orders',
  path: '/api/wa-dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboardNotificationsRoute =
  ApiWaDashboardNotificationsRouteImport.update({
    id: '/api/wa-dashboard/notifications',
    path: '/api/wa-dashboard/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWaDashboardLogoutRoute = ApiWaDashboardLogoutRouteImport.update({
  id: '/api/wa-dashboard/logout',
  path: '/api/wa-dashboard/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboardLoginRoute = ApiWaDashboardLoginRouteImport.update({
  id: '/api/wa-dashboard/login',
  path: '/api/wa-dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboardDiagnosticsRoute =
  ApiWaDashboardDiagnosticsRouteImport.update({
    id: '/api/wa-dashboard/diagnostics',
    path: '/api/wa-dashboard/diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWaDashboardCatalogRoute = ApiWaDashboardCatalogRouteImport.update({
  id: '/api/wa-dashboard/catalog',
  path: '/api/wa-dashboard/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboard2UploadRoute = ApiWaDashboard2UploadRouteImport.update({
  id: '/api/wa-dashboard-2/upload',
  path: '/api/wa-dashboard-2/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboard2SessionRoute = ApiWaDashboard2SessionRouteImport.update({
  id: '/api/wa-dashboard-2/session',
  path: '/api/wa-dashboard-2/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboard2OrdersRoute = ApiWaDashboard2OrdersRouteImport.update({
  id: '/api/wa-dashboard-2/orders',
  path: '/api/wa-dashboard-2/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboard2LogoutRoute = ApiWaDashboard2LogoutRouteImport.update({
  id: '/api/wa-dashboard-2/logout',
  path: '/api/wa-dashboard-2/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboard2LoginRoute = ApiWaDashboard2LoginRouteImport.update({
  id: '/api/wa-dashboard-2/login',
  path: '/api/wa-dashboard-2/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaDashboard2DiagnosticsRoute =
  ApiWaDashboard2DiagnosticsRouteImport.update({
    id: '/api/wa-dashboard-2/diagnostics',
    path: '/api/wa-dashboard-2/diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWaDashboard2CatalogRoute = ApiWaDashboard2CatalogRouteImport.update({
  id: '/api/wa-dashboard-2/catalog',
  path: '/api/wa-dashboard-2/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminWhatsappTemplatesRoute =
  ApiWaAdminWhatsappTemplatesRouteImport.update({
    id: '/api/wa-admin/whatsapp-templates',
    path: '/api/wa-admin/whatsapp-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWaAdminSessionRoute = ApiWaAdminSessionRouteImport.update({
  id: '/api/wa-admin/session',
  path: '/api/wa-admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminSendReviewMessageRoute =
  ApiWaAdminSendReviewMessageRouteImport.update({
    id: '/api/wa-admin/send-review-message',
    path: '/api/wa-admin/send-review-message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWaAdminReviewConnectionsRoute =
  ApiWaAdminReviewConnectionsRouteImport.update({
    id: '/api/wa-admin/review-connections',
    path: '/api/wa-admin/review-connections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWaAdminOverviewRoute = ApiWaAdminOverviewRouteImport.update({
  id: '/api/wa-admin/overview',
  path: '/api/wa-admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminMessageEventsRoute = ApiWaAdminMessageEventsRouteImport.update({
  id: '/api/wa-admin/message-events',
  path: '/api/wa-admin/message-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminLogsRoute = ApiWaAdminLogsRouteImport.update({
  id: '/api/wa-admin/logs',
  path: '/api/wa-admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminLogoutRoute = ApiWaAdminLogoutRouteImport.update({
  id: '/api/wa-admin/logout',
  path: '/api/wa-admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminLoginRoute = ApiWaAdminLoginRouteImport.update({
  id: '/api/wa-admin/login',
  path: '/api/wa-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminFlowTemplatesRoute = ApiWaAdminFlowTemplatesRouteImport.update({
  id: '/api/wa-admin/flow-templates',
  path: '/api/wa-admin/flow-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaAdminBusinessesRoute = ApiWaAdminBusinessesRouteImport.update({
  id: '/api/wa-admin/businesses',
  path: '/api/wa-admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlowTemplatesNewRoute = AdminFlowTemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFlowTemplatesRoute,
} as any)
const AdminFlowTemplatesTemplateIdRoute =
  AdminFlowTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AdminFlowTemplatesRoute,
  } as any)
const AdminBusinessesNewRoute = AdminBusinessesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBusinessesRoute,
} as any)
const AdminBusinessesBusinessIdRoute =
  AdminBusinessesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AdminBusinessesRoute,
  } as any)
const StoresPavoneAdminIndexRoute = StoresPavoneAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresPavoneAdminRoute,
} as any)
const StoresPavoneProductSlugRoute = StoresPavoneProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneCategorySlugRoute =
  StoresPavoneCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => StoresPavoneRoute,
  } as any)
const StoresPavoneAdminSettingsRoute =
  StoresPavoneAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const StoresPavoneAdminProductsRoute =
  StoresPavoneAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const StoresPavoneAdminOrdersRoute = StoresPavoneAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoresPavoneAdminRoute,
} as any)
const StoresPavoneAdminLoginRoute = StoresPavoneAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StoresPavoneAdminRoute,
} as any)
const StoresPavoneAdminInspirationsRoute =
  StoresPavoneAdminInspirationsRouteImport.update({
    id: '/inspirations',
    path: '/inspirations',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const StoresPavoneAdminCategoriesRoute =
  StoresPavoneAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const ApiWaDashboardOrdersOrderIdRoute =
  ApiWaDashboardOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => ApiWaDashboardOrdersRoute,
  } as any)
const ApiWaDashboard2OrdersOrderIdRoute =
  ApiWaDashboard2OrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => ApiWaDashboard2OrdersRoute,
  } as any)
const ApiWaAdminFlowTemplatesTemplateIdRoute =
  ApiWaAdminFlowTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => ApiWaAdminFlowTemplatesRoute,
  } as any)
const ApiWaAdminBusinessesBusinessIdRoute =
  ApiWaAdminBusinessesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => ApiWaAdminBusinessesRoute,
  } as any)
const AdminBusinessesBusinessIdProductsRoute =
  AdminBusinessesBusinessIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminBusinessesBusinessIdRoute,
  } as any)
const AdminBusinessesBusinessIdFlowBuilderRoute =
  AdminBusinessesBusinessIdFlowBuilderRouteImport.update({
    id: '/flow-builder',
    path: '/flow-builder',
    getParentRoute: () => AdminBusinessesBusinessIdRoute,
  } as any)
const AdminBusinessesBusinessIdCategoriesRoute =
  AdminBusinessesBusinessIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminBusinessesBusinessIdRoute,
  } as any)
const AdminBusinessesBusinessIdCatalogRoutesRoute =
  AdminBusinessesBusinessIdCatalogRoutesRouteImport.update({
    id: '/catalog-routes',
    path: '/catalog-routes',
    getParentRoute: () => AdminBusinessesBusinessIdRoute,
  } as any)
const AdminBusinessesBusinessIdCatalogRouteValuesRoute =
  AdminBusinessesBusinessIdCatalogRouteValuesRouteImport.update({
    id: '/catalog-route-values',
    path: '/catalog-route-values',
    getParentRoute: () => AdminBusinessesBusinessIdRoute,
  } as any)
const ApiWaAdminBusinessesBusinessIdFlowRoute =
  ApiWaAdminBusinessesBusinessIdFlowRouteImport.update({
    id: '/flow',
    path: '/flow',
    getParentRoute: () => ApiWaAdminBusinessesBusinessIdRoute,
  } as any)
const AdminFlowTemplatesTemplateIdVersionsVersionIdRoute =
  AdminFlowTemplatesTemplateIdVersionsVersionIdRouteImport.update({
    id: '/versions/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => AdminFlowTemplatesTemplateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard-2': typeof Dashboard2RouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/logsWABot': typeof LogsWABotRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/stores': typeof StoresRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/app-review-demo': typeof AdminAppReviewDemoRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/flow-templates': typeof AdminFlowTemplatesRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/whatsapp-templates': typeof AdminWhatsappTemplatesRoute
  '/dashboard-2/categories': typeof Dashboard2CategoriesRoute
  '/dashboard-2/delivery': typeof Dashboard2DeliveryRoute
  '/dashboard-2/orders': typeof Dashboard2OrdersRouteWithChildren
  '/dashboard-2/products': typeof Dashboard2ProductsRoute
  '/dashboard-2/settings': typeof Dashboard2SettingsRoute
  '/dashboard-2/simulator': typeof Dashboard2SimulatorRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/quotations/khadamati': typeof QuotationsKhadamatiRoute
  '/stores/pavone': typeof StoresPavoneRouteWithChildren
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/koubar-group': typeof WorkKoubarGroupRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
  '/work/uno400': typeof WorkUno400Route
  '/admin/': typeof AdminIndexRoute
  '/dashboard-2/': typeof Dashboard2IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/admin/businesses/$businessId': typeof AdminBusinessesBusinessIdRouteWithChildren
  '/admin/businesses/new': typeof AdminBusinessesNewRoute
  '/admin/flow-templates/$templateId': typeof AdminFlowTemplatesTemplateIdRouteWithChildren
  '/admin/flow-templates/new': typeof AdminFlowTemplatesNewRoute
  '/api/wa-admin/businesses': typeof ApiWaAdminBusinessesRouteWithChildren
  '/api/wa-admin/flow-templates': typeof ApiWaAdminFlowTemplatesRouteWithChildren
  '/api/wa-admin/login': typeof ApiWaAdminLoginRoute
  '/api/wa-admin/logout': typeof ApiWaAdminLogoutRoute
  '/api/wa-admin/logs': typeof ApiWaAdminLogsRoute
  '/api/wa-admin/message-events': typeof ApiWaAdminMessageEventsRoute
  '/api/wa-admin/overview': typeof ApiWaAdminOverviewRoute
  '/api/wa-admin/review-connections': typeof ApiWaAdminReviewConnectionsRoute
  '/api/wa-admin/send-review-message': typeof ApiWaAdminSendReviewMessageRoute
  '/api/wa-admin/session': typeof ApiWaAdminSessionRoute
  '/api/wa-admin/whatsapp-templates': typeof ApiWaAdminWhatsappTemplatesRoute
  '/api/wa-dashboard-2/catalog': typeof ApiWaDashboard2CatalogRoute
  '/api/wa-dashboard-2/diagnostics': typeof ApiWaDashboard2DiagnosticsRoute
  '/api/wa-dashboard-2/login': typeof ApiWaDashboard2LoginRoute
  '/api/wa-dashboard-2/logout': typeof ApiWaDashboard2LogoutRoute
  '/api/wa-dashboard-2/orders': typeof ApiWaDashboard2OrdersRouteWithChildren
  '/api/wa-dashboard-2/session': typeof ApiWaDashboard2SessionRoute
  '/api/wa-dashboard-2/upload': typeof ApiWaDashboard2UploadRoute
  '/api/wa-dashboard/catalog': typeof ApiWaDashboardCatalogRoute
  '/api/wa-dashboard/diagnostics': typeof ApiWaDashboardDiagnosticsRoute
  '/api/wa-dashboard/login': typeof ApiWaDashboardLoginRoute
  '/api/wa-dashboard/logout': typeof ApiWaDashboardLogoutRoute
  '/api/wa-dashboard/notifications': typeof ApiWaDashboardNotificationsRoute
  '/api/wa-dashboard/orders': typeof ApiWaDashboardOrdersRouteWithChildren
  '/api/wa-dashboard/session': typeof ApiWaDashboardSessionRoute
  '/api/wa-dashboard/upload': typeof ApiWaDashboardUploadRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/whatsapp/webhook-2': typeof ApiWhatsappWebhook2Route
  '/dashboard-2/orders/$orderId': typeof Dashboard2OrdersOrderIdRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/stores/pavone/admin': typeof StoresPavoneAdminRouteWithChildren
  '/stores/pavone/shop': typeof StoresPavoneShopRoute
  '/stores/pavone/wishlist': typeof StoresPavoneWishlistRoute
  '/stores/pavone/': typeof StoresPavoneIndexRoute
  '/admin/businesses/$businessId/catalog-route-values': typeof AdminBusinessesBusinessIdCatalogRouteValuesRoute
  '/admin/businesses/$businessId/catalog-routes': typeof AdminBusinessesBusinessIdCatalogRoutesRoute
  '/admin/businesses/$businessId/categories': typeof AdminBusinessesBusinessIdCategoriesRoute
  '/admin/businesses/$businessId/flow-builder': typeof AdminBusinessesBusinessIdFlowBuilderRoute
  '/admin/businesses/$businessId/products': typeof AdminBusinessesBusinessIdProductsRoute
  '/api/wa-admin/businesses/$businessId': typeof ApiWaAdminBusinessesBusinessIdRouteWithChildren
  '/api/wa-admin/flow-templates/$templateId': typeof ApiWaAdminFlowTemplatesTemplateIdRoute
  '/api/wa-dashboard-2/orders/$orderId': typeof ApiWaDashboard2OrdersOrderIdRoute
  '/api/wa-dashboard/orders/$orderId': typeof ApiWaDashboardOrdersOrderIdRoute
  '/stores/pavone/admin/categories': typeof StoresPavoneAdminCategoriesRoute
  '/stores/pavone/admin/inspirations': typeof StoresPavoneAdminInspirationsRoute
  '/stores/pavone/admin/login': typeof StoresPavoneAdminLoginRoute
  '/stores/pavone/admin/orders': typeof StoresPavoneAdminOrdersRoute
  '/stores/pavone/admin/products': typeof StoresPavoneAdminProductsRoute
  '/stores/pavone/admin/settings': typeof StoresPavoneAdminSettingsRoute
  '/stores/pavone/category/$slug': typeof StoresPavoneCategorySlugRoute
  '/stores/pavone/product/$slug': typeof StoresPavoneProductSlugRoute
  '/stores/pavone/admin/': typeof StoresPavoneAdminIndexRoute
  '/admin/flow-templates/$templateId/versions/$versionId': typeof AdminFlowTemplatesTemplateIdVersionsVersionIdRoute
  '/api/wa-admin/businesses/$businessId/flow': typeof ApiWaAdminBusinessesBusinessIdFlowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/logsWABot': typeof LogsWABotRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/app-review-demo': typeof AdminAppReviewDemoRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/flow-templates': typeof AdminFlowTemplatesRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/whatsapp-templates': typeof AdminWhatsappTemplatesRoute
  '/dashboard-2/categories': typeof Dashboard2CategoriesRoute
  '/dashboard-2/delivery': typeof Dashboard2DeliveryRoute
  '/dashboard-2/orders': typeof Dashboard2OrdersRouteWithChildren
  '/dashboard-2/products': typeof Dashboard2ProductsRoute
  '/dashboard-2/settings': typeof Dashboard2SettingsRoute
  '/dashboard-2/simulator': typeof Dashboard2SimulatorRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/quotations/khadamati': typeof QuotationsKhadamatiRoute
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/koubar-group': typeof WorkKoubarGroupRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
  '/work/uno400': typeof WorkUno400Route
  '/admin': typeof AdminIndexRoute
  '/dashboard-2': typeof Dashboard2IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/stores': typeof StoresIndexRoute
  '/admin/businesses/$businessId': typeof AdminBusinessesBusinessIdRouteWithChildren
  '/admin/businesses/new': typeof AdminBusinessesNewRoute
  '/admin/flow-templates/$templateId': typeof AdminFlowTemplatesTemplateIdRouteWithChildren
  '/admin/flow-templates/new': typeof AdminFlowTemplatesNewRoute
  '/api/wa-admin/businesses': typeof ApiWaAdminBusinessesRouteWithChildren
  '/api/wa-admin/flow-templates': typeof ApiWaAdminFlowTemplatesRouteWithChildren
  '/api/wa-admin/login': typeof ApiWaAdminLoginRoute
  '/api/wa-admin/logout': typeof ApiWaAdminLogoutRoute
  '/api/wa-admin/logs': typeof ApiWaAdminLogsRoute
  '/api/wa-admin/message-events': typeof ApiWaAdminMessageEventsRoute
  '/api/wa-admin/overview': typeof ApiWaAdminOverviewRoute
  '/api/wa-admin/review-connections': typeof ApiWaAdminReviewConnectionsRoute
  '/api/wa-admin/send-review-message': typeof ApiWaAdminSendReviewMessageRoute
  '/api/wa-admin/session': typeof ApiWaAdminSessionRoute
  '/api/wa-admin/whatsapp-templates': typeof ApiWaAdminWhatsappTemplatesRoute
  '/api/wa-dashboard-2/catalog': typeof ApiWaDashboard2CatalogRoute
  '/api/wa-dashboard-2/diagnostics': typeof ApiWaDashboard2DiagnosticsRoute
  '/api/wa-dashboard-2/login': typeof ApiWaDashboard2LoginRoute
  '/api/wa-dashboard-2/logout': typeof ApiWaDashboard2LogoutRoute
  '/api/wa-dashboard-2/orders': typeof ApiWaDashboard2OrdersRouteWithChildren
  '/api/wa-dashboard-2/session': typeof ApiWaDashboard2SessionRoute
  '/api/wa-dashboard-2/upload': typeof ApiWaDashboard2UploadRoute
  '/api/wa-dashboard/catalog': typeof ApiWaDashboardCatalogRoute
  '/api/wa-dashboard/diagnostics': typeof ApiWaDashboardDiagnosticsRoute
  '/api/wa-dashboard/login': typeof ApiWaDashboardLoginRoute
  '/api/wa-dashboard/logout': typeof ApiWaDashboardLogoutRoute
  '/api/wa-dashboard/notifications': typeof ApiWaDashboardNotificationsRoute
  '/api/wa-dashboard/orders': typeof ApiWaDashboardOrdersRouteWithChildren
  '/api/wa-dashboard/session': typeof ApiWaDashboardSessionRoute
  '/api/wa-dashboard/upload': typeof ApiWaDashboardUploadRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/whatsapp/webhook-2': typeof ApiWhatsappWebhook2Route
  '/dashboard-2/orders/$orderId': typeof Dashboard2OrdersOrderIdRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/stores/pavone/shop': typeof StoresPavoneShopRoute
  '/stores/pavone/wishlist': typeof StoresPavoneWishlistRoute
  '/stores/pavone': typeof StoresPavoneIndexRoute
  '/admin/businesses/$businessId/catalog-route-values': typeof AdminBusinessesBusinessIdCatalogRouteValuesRoute
  '/admin/businesses/$businessId/catalog-routes': typeof AdminBusinessesBusinessIdCatalogRoutesRoute
  '/admin/businesses/$businessId/categories': typeof AdminBusinessesBusinessIdCategoriesRoute
  '/admin/businesses/$businessId/flow-builder': typeof AdminBusinessesBusinessIdFlowBuilderRoute
  '/admin/businesses/$businessId/products': typeof AdminBusinessesBusinessIdProductsRoute
  '/api/wa-admin/businesses/$businessId': typeof ApiWaAdminBusinessesBusinessIdRouteWithChildren
  '/api/wa-admin/flow-templates/$templateId': typeof ApiWaAdminFlowTemplatesTemplateIdRoute
  '/api/wa-dashboard-2/orders/$orderId': typeof ApiWaDashboard2OrdersOrderIdRoute
  '/api/wa-dashboard/orders/$orderId': typeof ApiWaDashboardOrdersOrderIdRoute
  '/stores/pavone/admin/categories': typeof StoresPavoneAdminCategoriesRoute
  '/stores/pavone/admin/inspirations': typeof StoresPavoneAdminInspirationsRoute
  '/stores/pavone/admin/login': typeof StoresPavoneAdminLoginRoute
  '/stores/pavone/admin/orders': typeof StoresPavoneAdminOrdersRoute
  '/stores/pavone/admin/products': typeof StoresPavoneAdminProductsRoute
  '/stores/pavone/admin/settings': typeof StoresPavoneAdminSettingsRoute
  '/stores/pavone/category/$slug': typeof StoresPavoneCategorySlugRoute
  '/stores/pavone/product/$slug': typeof StoresPavoneProductSlugRoute
  '/stores/pavone/admin': typeof StoresPavoneAdminIndexRoute
  '/admin/flow-templates/$templateId/versions/$versionId': typeof AdminFlowTemplatesTemplateIdVersionsVersionIdRoute
  '/api/wa-admin/businesses/$businessId/flow': typeof ApiWaAdminBusinessesBusinessIdFlowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard-2': typeof Dashboard2RouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/logsWABot': typeof LogsWABotRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/stores': typeof StoresRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/app-review-demo': typeof AdminAppReviewDemoRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/flow-templates': typeof AdminFlowTemplatesRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/whatsapp-templates': typeof AdminWhatsappTemplatesRoute
  '/dashboard-2/categories': typeof Dashboard2CategoriesRoute
  '/dashboard-2/delivery': typeof Dashboard2DeliveryRoute
  '/dashboard-2/orders': typeof Dashboard2OrdersRouteWithChildren
  '/dashboard-2/products': typeof Dashboard2ProductsRoute
  '/dashboard-2/settings': typeof Dashboard2SettingsRoute
  '/dashboard-2/simulator': typeof Dashboard2SimulatorRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/quotations/khadamati': typeof QuotationsKhadamatiRoute
  '/stores/pavone': typeof StoresPavoneRouteWithChildren
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/koubar-group': typeof WorkKoubarGroupRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
  '/work/uno400': typeof WorkUno400Route
  '/admin/': typeof AdminIndexRoute
  '/dashboard-2/': typeof Dashboard2IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/admin/businesses/$businessId': typeof AdminBusinessesBusinessIdRouteWithChildren
  '/admin/businesses/new': typeof AdminBusinessesNewRoute
  '/admin/flow-templates/$templateId': typeof AdminFlowTemplatesTemplateIdRouteWithChildren
  '/admin/flow-templates/new': typeof AdminFlowTemplatesNewRoute
  '/api/wa-admin/businesses': typeof ApiWaAdminBusinessesRouteWithChildren
  '/api/wa-admin/flow-templates': typeof ApiWaAdminFlowTemplatesRouteWithChildren
  '/api/wa-admin/login': typeof ApiWaAdminLoginRoute
  '/api/wa-admin/logout': typeof ApiWaAdminLogoutRoute
  '/api/wa-admin/logs': typeof ApiWaAdminLogsRoute
  '/api/wa-admin/message-events': typeof ApiWaAdminMessageEventsRoute
  '/api/wa-admin/overview': typeof ApiWaAdminOverviewRoute
  '/api/wa-admin/review-connections': typeof ApiWaAdminReviewConnectionsRoute
  '/api/wa-admin/send-review-message': typeof ApiWaAdminSendReviewMessageRoute
  '/api/wa-admin/session': typeof ApiWaAdminSessionRoute
  '/api/wa-admin/whatsapp-templates': typeof ApiWaAdminWhatsappTemplatesRoute
  '/api/wa-dashboard-2/catalog': typeof ApiWaDashboard2CatalogRoute
  '/api/wa-dashboard-2/diagnostics': typeof ApiWaDashboard2DiagnosticsRoute
  '/api/wa-dashboard-2/login': typeof ApiWaDashboard2LoginRoute
  '/api/wa-dashboard-2/logout': typeof ApiWaDashboard2LogoutRoute
  '/api/wa-dashboard-2/orders': typeof ApiWaDashboard2OrdersRouteWithChildren
  '/api/wa-dashboard-2/session': typeof ApiWaDashboard2SessionRoute
  '/api/wa-dashboard-2/upload': typeof ApiWaDashboard2UploadRoute
  '/api/wa-dashboard/catalog': typeof ApiWaDashboardCatalogRoute
  '/api/wa-dashboard/diagnostics': typeof ApiWaDashboardDiagnosticsRoute
  '/api/wa-dashboard/login': typeof ApiWaDashboardLoginRoute
  '/api/wa-dashboard/logout': typeof ApiWaDashboardLogoutRoute
  '/api/wa-dashboard/notifications': typeof ApiWaDashboardNotificationsRoute
  '/api/wa-dashboard/orders': typeof ApiWaDashboardOrdersRouteWithChildren
  '/api/wa-dashboard/session': typeof ApiWaDashboardSessionRoute
  '/api/wa-dashboard/upload': typeof ApiWaDashboardUploadRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/whatsapp/webhook-2': typeof ApiWhatsappWebhook2Route
  '/dashboard-2/orders/$orderId': typeof Dashboard2OrdersOrderIdRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/stores/pavone/admin': typeof StoresPavoneAdminRouteWithChildren
  '/stores/pavone/shop': typeof StoresPavoneShopRoute
  '/stores/pavone/wishlist': typeof StoresPavoneWishlistRoute
  '/stores/pavone/': typeof StoresPavoneIndexRoute
  '/admin/businesses/$businessId/catalog-route-values': typeof AdminBusinessesBusinessIdCatalogRouteValuesRoute
  '/admin/businesses/$businessId/catalog-routes': typeof AdminBusinessesBusinessIdCatalogRoutesRoute
  '/admin/businesses/$businessId/categories': typeof AdminBusinessesBusinessIdCategoriesRoute
  '/admin/businesses/$businessId/flow-builder': typeof AdminBusinessesBusinessIdFlowBuilderRoute
  '/admin/businesses/$businessId/products': typeof AdminBusinessesBusinessIdProductsRoute
  '/api/wa-admin/businesses/$businessId': typeof ApiWaAdminBusinessesBusinessIdRouteWithChildren
  '/api/wa-admin/flow-templates/$templateId': typeof ApiWaAdminFlowTemplatesTemplateIdRoute
  '/api/wa-dashboard-2/orders/$orderId': typeof ApiWaDashboard2OrdersOrderIdRoute
  '/api/wa-dashboard/orders/$orderId': typeof ApiWaDashboardOrdersOrderIdRoute
  '/stores/pavone/admin/categories': typeof StoresPavoneAdminCategoriesRoute
  '/stores/pavone/admin/inspirations': typeof StoresPavoneAdminInspirationsRoute
  '/stores/pavone/admin/login': typeof StoresPavoneAdminLoginRoute
  '/stores/pavone/admin/orders': typeof StoresPavoneAdminOrdersRoute
  '/stores/pavone/admin/products': typeof StoresPavoneAdminProductsRoute
  '/stores/pavone/admin/settings': typeof StoresPavoneAdminSettingsRoute
  '/stores/pavone/category/$slug': typeof StoresPavoneCategorySlugRoute
  '/stores/pavone/product/$slug': typeof StoresPavoneProductSlugRoute
  '/stores/pavone/admin/': typeof StoresPavoneAdminIndexRoute
  '/admin/flow-templates/$templateId/versions/$versionId': typeof AdminFlowTemplatesTemplateIdVersionsVersionIdRoute
  '/api/wa-admin/businesses/$businessId/flow': typeof ApiWaAdminBusinessesBusinessIdFlowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/dashboard-2'
    | '/data-deletion'
    | '/logsWABot'
    | '/privacy'
    | '/privacy-policy'
    | '/spreadsheet'
    | '/stores'
    | '/terms-and-conditions'
    | '/admin/app-review-demo'
    | '/admin/businesses'
    | '/admin/flow-templates'
    | '/admin/logs'
    | '/admin/whatsapp-templates'
    | '/dashboard-2/categories'
    | '/dashboard-2/delivery'
    | '/dashboard-2/orders'
    | '/dashboard-2/products'
    | '/dashboard-2/settings'
    | '/dashboard-2/simulator'
    | '/dashboard/categories'
    | '/dashboard/delivery'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/simulator'
    | '/menus/marleys'
    | '/quotations/khadamati'
    | '/stores/pavone'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/koubar-group'
    | '/work/snapgo'
    | '/work/tijarati-pro'
    | '/work/uno400'
    | '/admin/'
    | '/dashboard-2/'
    | '/dashboard/'
    | '/stores/'
    | '/admin/businesses/$businessId'
    | '/admin/businesses/new'
    | '/admin/flow-templates/$templateId'
    | '/admin/flow-templates/new'
    | '/api/wa-admin/businesses'
    | '/api/wa-admin/flow-templates'
    | '/api/wa-admin/login'
    | '/api/wa-admin/logout'
    | '/api/wa-admin/logs'
    | '/api/wa-admin/message-events'
    | '/api/wa-admin/overview'
    | '/api/wa-admin/review-connections'
    | '/api/wa-admin/send-review-message'
    | '/api/wa-admin/session'
    | '/api/wa-admin/whatsapp-templates'
    | '/api/wa-dashboard-2/catalog'
    | '/api/wa-dashboard-2/diagnostics'
    | '/api/wa-dashboard-2/login'
    | '/api/wa-dashboard-2/logout'
    | '/api/wa-dashboard-2/orders'
    | '/api/wa-dashboard-2/session'
    | '/api/wa-dashboard-2/upload'
    | '/api/wa-dashboard/catalog'
    | '/api/wa-dashboard/diagnostics'
    | '/api/wa-dashboard/login'
    | '/api/wa-dashboard/logout'
    | '/api/wa-dashboard/notifications'
    | '/api/wa-dashboard/orders'
    | '/api/wa-dashboard/session'
    | '/api/wa-dashboard/upload'
    | '/api/whatsapp/webhook'
    | '/api/whatsapp/webhook-2'
    | '/dashboard-2/orders/$orderId'
    | '/dashboard/orders/$orderId'
    | '/stores/pavone/admin'
    | '/stores/pavone/shop'
    | '/stores/pavone/wishlist'
    | '/stores/pavone/'
    | '/admin/businesses/$businessId/catalog-route-values'
    | '/admin/businesses/$businessId/catalog-routes'
    | '/admin/businesses/$businessId/categories'
    | '/admin/businesses/$businessId/flow-builder'
    | '/admin/businesses/$businessId/products'
    | '/api/wa-admin/businesses/$businessId'
    | '/api/wa-admin/flow-templates/$templateId'
    | '/api/wa-dashboard-2/orders/$orderId'
    | '/api/wa-dashboard/orders/$orderId'
    | '/stores/pavone/admin/categories'
    | '/stores/pavone/admin/inspirations'
    | '/stores/pavone/admin/login'
    | '/stores/pavone/admin/orders'
    | '/stores/pavone/admin/products'
    | '/stores/pavone/admin/settings'
    | '/stores/pavone/category/$slug'
    | '/stores/pavone/product/$slug'
    | '/stores/pavone/admin/'
    | '/admin/flow-templates/$templateId/versions/$versionId'
    | '/api/wa-admin/businesses/$businessId/flow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/data-deletion'
    | '/logsWABot'
    | '/privacy'
    | '/privacy-policy'
    | '/spreadsheet'
    | '/terms-and-conditions'
    | '/admin/app-review-demo'
    | '/admin/businesses'
    | '/admin/flow-templates'
    | '/admin/logs'
    | '/admin/whatsapp-templates'
    | '/dashboard-2/categories'
    | '/dashboard-2/delivery'
    | '/dashboard-2/orders'
    | '/dashboard-2/products'
    | '/dashboard-2/settings'
    | '/dashboard-2/simulator'
    | '/dashboard/categories'
    | '/dashboard/delivery'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/simulator'
    | '/menus/marleys'
    | '/quotations/khadamati'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/koubar-group'
    | '/work/snapgo'
    | '/work/tijarati-pro'
    | '/work/uno400'
    | '/admin'
    | '/dashboard-2'
    | '/dashboard'
    | '/stores'
    | '/admin/businesses/$businessId'
    | '/admin/businesses/new'
    | '/admin/flow-templates/$templateId'
    | '/admin/flow-templates/new'
    | '/api/wa-admin/businesses'
    | '/api/wa-admin/flow-templates'
    | '/api/wa-admin/login'
    | '/api/wa-admin/logout'
    | '/api/wa-admin/logs'
    | '/api/wa-admin/message-events'
    | '/api/wa-admin/overview'
    | '/api/wa-admin/review-connections'
    | '/api/wa-admin/send-review-message'
    | '/api/wa-admin/session'
    | '/api/wa-admin/whatsapp-templates'
    | '/api/wa-dashboard-2/catalog'
    | '/api/wa-dashboard-2/diagnostics'
    | '/api/wa-dashboard-2/login'
    | '/api/wa-dashboard-2/logout'
    | '/api/wa-dashboard-2/orders'
    | '/api/wa-dashboard-2/session'
    | '/api/wa-dashboard-2/upload'
    | '/api/wa-dashboard/catalog'
    | '/api/wa-dashboard/diagnostics'
    | '/api/wa-dashboard/login'
    | '/api/wa-dashboard/logout'
    | '/api/wa-dashboard/notifications'
    | '/api/wa-dashboard/orders'
    | '/api/wa-dashboard/session'
    | '/api/wa-dashboard/upload'
    | '/api/whatsapp/webhook'
    | '/api/whatsapp/webhook-2'
    | '/dashboard-2/orders/$orderId'
    | '/dashboard/orders/$orderId'
    | '/stores/pavone/shop'
    | '/stores/pavone/wishlist'
    | '/stores/pavone'
    | '/admin/businesses/$businessId/catalog-route-values'
    | '/admin/businesses/$businessId/catalog-routes'
    | '/admin/businesses/$businessId/categories'
    | '/admin/businesses/$businessId/flow-builder'
    | '/admin/businesses/$businessId/products'
    | '/api/wa-admin/businesses/$businessId'
    | '/api/wa-admin/flow-templates/$templateId'
    | '/api/wa-dashboard-2/orders/$orderId'
    | '/api/wa-dashboard/orders/$orderId'
    | '/stores/pavone/admin/categories'
    | '/stores/pavone/admin/inspirations'
    | '/stores/pavone/admin/login'
    | '/stores/pavone/admin/orders'
    | '/stores/pavone/admin/products'
    | '/stores/pavone/admin/settings'
    | '/stores/pavone/category/$slug'
    | '/stores/pavone/product/$slug'
    | '/stores/pavone/admin'
    | '/admin/flow-templates/$templateId/versions/$versionId'
    | '/api/wa-admin/businesses/$businessId/flow'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/dashboard-2'
    | '/data-deletion'
    | '/logsWABot'
    | '/privacy'
    | '/privacy-policy'
    | '/spreadsheet'
    | '/stores'
    | '/terms-and-conditions'
    | '/admin/app-review-demo'
    | '/admin/businesses'
    | '/admin/flow-templates'
    | '/admin/logs'
    | '/admin/whatsapp-templates'
    | '/dashboard-2/categories'
    | '/dashboard-2/delivery'
    | '/dashboard-2/orders'
    | '/dashboard-2/products'
    | '/dashboard-2/settings'
    | '/dashboard-2/simulator'
    | '/dashboard/categories'
    | '/dashboard/delivery'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/simulator'
    | '/menus/marleys'
    | '/quotations/khadamati'
    | '/stores/pavone'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/koubar-group'
    | '/work/snapgo'
    | '/work/tijarati-pro'
    | '/work/uno400'
    | '/admin/'
    | '/dashboard-2/'
    | '/dashboard/'
    | '/stores/'
    | '/admin/businesses/$businessId'
    | '/admin/businesses/new'
    | '/admin/flow-templates/$templateId'
    | '/admin/flow-templates/new'
    | '/api/wa-admin/businesses'
    | '/api/wa-admin/flow-templates'
    | '/api/wa-admin/login'
    | '/api/wa-admin/logout'
    | '/api/wa-admin/logs'
    | '/api/wa-admin/message-events'
    | '/api/wa-admin/overview'
    | '/api/wa-admin/review-connections'
    | '/api/wa-admin/send-review-message'
    | '/api/wa-admin/session'
    | '/api/wa-admin/whatsapp-templates'
    | '/api/wa-dashboard-2/catalog'
    | '/api/wa-dashboard-2/diagnostics'
    | '/api/wa-dashboard-2/login'
    | '/api/wa-dashboard-2/logout'
    | '/api/wa-dashboard-2/orders'
    | '/api/wa-dashboard-2/session'
    | '/api/wa-dashboard-2/upload'
    | '/api/wa-dashboard/catalog'
    | '/api/wa-dashboard/diagnostics'
    | '/api/wa-dashboard/login'
    | '/api/wa-dashboard/logout'
    | '/api/wa-dashboard/notifications'
    | '/api/wa-dashboard/orders'
    | '/api/wa-dashboard/session'
    | '/api/wa-dashboard/upload'
    | '/api/whatsapp/webhook'
    | '/api/whatsapp/webhook-2'
    | '/dashboard-2/orders/$orderId'
    | '/dashboard/orders/$orderId'
    | '/stores/pavone/admin'
    | '/stores/pavone/shop'
    | '/stores/pavone/wishlist'
    | '/stores/pavone/'
    | '/admin/businesses/$businessId/catalog-route-values'
    | '/admin/businesses/$businessId/catalog-routes'
    | '/admin/businesses/$businessId/categories'
    | '/admin/businesses/$businessId/flow-builder'
    | '/admin/businesses/$businessId/products'
    | '/api/wa-admin/businesses/$businessId'
    | '/api/wa-admin/flow-templates/$templateId'
    | '/api/wa-dashboard-2/orders/$orderId'
    | '/api/wa-dashboard/orders/$orderId'
    | '/stores/pavone/admin/categories'
    | '/stores/pavone/admin/inspirations'
    | '/stores/pavone/admin/login'
    | '/stores/pavone/admin/orders'
    | '/stores/pavone/admin/products'
    | '/stores/pavone/admin/settings'
    | '/stores/pavone/category/$slug'
    | '/stores/pavone/product/$slug'
    | '/stores/pavone/admin/'
    | '/admin/flow-templates/$templateId/versions/$versionId'
    | '/api/wa-admin/businesses/$businessId/flow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  Dashboard2Route: typeof Dashboard2RouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  LogsWABotRoute: typeof LogsWABotRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SpreadsheetRoute: typeof SpreadsheetRoute
  StoresRoute: typeof StoresRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  MenusMarleysRoute: typeof MenusMarleysRoute
  QuotationsKhadamatiRoute: typeof QuotationsKhadamatiRoute
  WorkDataInsightsRoute: typeof WorkDataInsightsRoute
  WorkDetailingLabRoute: typeof WorkDetailingLabRoute
  WorkKoubarGroupRoute: typeof WorkKoubarGroupRoute
  WorkSnapgoRoute: typeof WorkSnapgoRoute
  WorkTijaratiProRoute: typeof WorkTijaratiProRoute
  WorkUno400Route: typeof WorkUno400Route
  ApiWaAdminBusinessesRoute: typeof ApiWaAdminBusinessesRouteWithChildren
  ApiWaAdminFlowTemplatesRoute: typeof ApiWaAdminFlowTemplatesRouteWithChildren
  ApiWaAdminLoginRoute: typeof ApiWaAdminLoginRoute
  ApiWaAdminLogoutRoute: typeof ApiWaAdminLogoutRoute
  ApiWaAdminLogsRoute: typeof ApiWaAdminLogsRoute
  ApiWaAdminMessageEventsRoute: typeof ApiWaAdminMessageEventsRoute
  ApiWaAdminOverviewRoute: typeof ApiWaAdminOverviewRoute
  ApiWaAdminReviewConnectionsRoute: typeof ApiWaAdminReviewConnectionsRoute
  ApiWaAdminSendReviewMessageRoute: typeof ApiWaAdminSendReviewMessageRoute
  ApiWaAdminSessionRoute: typeof ApiWaAdminSessionRoute
  ApiWaAdminWhatsappTemplatesRoute: typeof ApiWaAdminWhatsappTemplatesRoute
  ApiWaDashboard2CatalogRoute: typeof ApiWaDashboard2CatalogRoute
  ApiWaDashboard2DiagnosticsRoute: typeof ApiWaDashboard2DiagnosticsRoute
  ApiWaDashboard2LoginRoute: typeof ApiWaDashboard2LoginRoute
  ApiWaDashboard2LogoutRoute: typeof ApiWaDashboard2LogoutRoute
  ApiWaDashboard2OrdersRoute: typeof ApiWaDashboard2OrdersRouteWithChildren
  ApiWaDashboard2SessionRoute: typeof ApiWaDashboard2SessionRoute
  ApiWaDashboard2UploadRoute: typeof ApiWaDashboard2UploadRoute
  ApiWaDashboardCatalogRoute: typeof ApiWaDashboardCatalogRoute
  ApiWaDashboardDiagnosticsRoute: typeof ApiWaDashboardDiagnosticsRoute
  ApiWaDashboardLoginRoute: typeof ApiWaDashboardLoginRoute
  ApiWaDashboardLogoutRoute: typeof ApiWaDashboardLogoutRoute
  ApiWaDashboardNotificationsRoute: typeof ApiWaDashboardNotificationsRoute
  ApiWaDashboardOrdersRoute: typeof ApiWaDashboardOrdersRouteWithChildren
  ApiWaDashboardSessionRoute: typeof ApiWaDashboardSessionRoute
  ApiWaDashboardUploadRoute: typeof ApiWaDashboardUploadRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiWhatsappWebhook2Route: typeof ApiWhatsappWebhook2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreadsheet': {
      id: '/spreadsheet'
      path: '/spreadsheet'
      fullPath: '/spreadsheet'
      preLoaderRoute: typeof SpreadsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logsWABot': {
      id: '/logsWABot'
      path: '/logsWABot'
      fullPath: '/logsWABot'
      preLoaderRoute: typeof LogsWABotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-2': {
      id: '/dashboard-2'
      path: '/dashboard-2'
      fullPath: '/dashboard-2'
      preLoaderRoute: typeof Dashboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof StoresRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard-2/': {
      id: '/dashboard-2/'
      path: '/'
      fullPath: '/dashboard-2/'
      preLoaderRoute: typeof Dashboard2IndexRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/work/uno400': {
      id: '/work/uno400'
      path: '/work/uno400'
      fullPath: '/work/uno400'
      preLoaderRoute: typeof WorkUno400RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/tijarati-pro': {
      id: '/work/tijarati-pro'
      path: '/work/tijarati-pro'
      fullPath: '/work/tijarati-pro'
      preLoaderRoute: typeof WorkTijaratiProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/snapgo': {
      id: '/work/snapgo'
      path: '/work/snapgo'
      fullPath: '/work/snapgo'
      preLoaderRoute: typeof WorkSnapgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/koubar-group': {
      id: '/work/koubar-group'
      path: '/work/koubar-group'
      fullPath: '/work/koubar-group'
      preLoaderRoute: typeof WorkKoubarGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/detailing-lab': {
      id: '/work/detailing-lab'
      path: '/work/detailing-lab'
      fullPath: '/work/detailing-lab'
      preLoaderRoute: typeof WorkDetailingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/data-insights': {
      id: '/work/data-insights'
      path: '/work/data-insights'
      fullPath: '/work/data-insights'
      preLoaderRoute: typeof WorkDataInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/pavone': {
      id: '/stores/pavone'
      path: '/pavone'
      fullPath: '/stores/pavone'
      preLoaderRoute: typeof StoresPavoneRouteImport
      parentRoute: typeof StoresRoute
    }
    '/quotations/khadamati': {
      id: '/quotations/khadamati'
      path: '/quotations/khadamati'
      fullPath: '/quotations/khadamati'
      preLoaderRoute: typeof QuotationsKhadamatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus/marleys': {
      id: '/menus/marleys'
      path: '/menus/marleys'
      fullPath: '/menus/marleys'
      preLoaderRoute: typeof MenusMarleysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/simulator': {
      id: '/dashboard/simulator'
      path: '/simulator'
      fullPath: '/dashboard/simulator'
      preLoaderRoute: typeof DashboardSimulatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/delivery': {
      id: '/dashboard/delivery'
      path: '/delivery'
      fullPath: '/dashboard/delivery'
      preLoaderRoute: typeof DashboardDeliveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard-2/simulator': {
      id: '/dashboard-2/simulator'
      path: '/simulator'
      fullPath: '/dashboard-2/simulator'
      preLoaderRoute: typeof Dashboard2SimulatorRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/dashboard-2/settings': {
      id: '/dashboard-2/settings'
      path: '/settings'
      fullPath: '/dashboard-2/settings'
      preLoaderRoute: typeof Dashboard2SettingsRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/dashboard-2/products': {
      id: '/dashboard-2/products'
      path: '/products'
      fullPath: '/dashboard-2/products'
      preLoaderRoute: typeof Dashboard2ProductsRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/dashboard-2/orders': {
      id: '/dashboard-2/orders'
      path: '/orders'
      fullPath: '/dashboard-2/orders'
      preLoaderRoute: typeof Dashboard2OrdersRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/dashboard-2/delivery': {
      id: '/dashboard-2/delivery'
      path: '/delivery'
      fullPath: '/dashboard-2/delivery'
      preLoaderRoute: typeof Dashboard2DeliveryRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/dashboard-2/categories': {
      id: '/dashboard-2/categories'
      path: '/categories'
      fullPath: '/dashboard-2/categories'
      preLoaderRoute: typeof Dashboard2CategoriesRouteImport
      parentRoute: typeof Dashboard2Route
    }
    '/admin/whatsapp-templates': {
      id: '/admin/whatsapp-templates'
      path: '/whatsapp-templates'
      fullPath: '/admin/whatsapp-templates'
      preLoaderRoute: typeof AdminWhatsappTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flow-templates': {
      id: '/admin/flow-templates'
      path: '/flow-templates'
      fullPath: '/admin/flow-templates'
      preLoaderRoute: typeof AdminFlowTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/app-review-demo': {
      id: '/admin/app-review-demo'
      path: '/app-review-demo'
      fullPath: '/admin/app-review-demo'
      preLoaderRoute: typeof AdminAppReviewDemoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stores/pavone/': {
      id: '/stores/pavone/'
      path: '/'
      fullPath: '/stores/pavone/'
      preLoaderRoute: typeof StoresPavoneIndexRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/wishlist': {
      id: '/stores/pavone/wishlist'
      path: '/wishlist'
      fullPath: '/stores/pavone/wishlist'
      preLoaderRoute: typeof StoresPavoneWishlistRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/shop': {
      id: '/stores/pavone/shop'
      path: '/shop'
      fullPath: '/stores/pavone/shop'
      preLoaderRoute: typeof StoresPavoneShopRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/admin': {
      id: '/stores/pavone/admin'
      path: '/admin'
      fullPath: '/stores/pavone/admin'
      preLoaderRoute: typeof StoresPavoneAdminRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/dashboard/orders/$orderId': {
      id: '/dashboard/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof DashboardOrdersOrderIdRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard-2/orders/$orderId': {
      id: '/dashboard-2/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard-2/orders/$orderId'
      preLoaderRoute: typeof Dashboard2OrdersOrderIdRouteImport
      parentRoute: typeof Dashboard2OrdersRoute
    }
    '/api/whatsapp/webhook-2': {
      id: '/api/whatsapp/webhook-2'
      path: '/api/whatsapp/webhook-2'
      fullPath: '/api/whatsapp/webhook-2'
      preLoaderRoute: typeof ApiWhatsappWebhook2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/upload': {
      id: '/api/wa-dashboard/upload'
      path: '/api/wa-dashboard/upload'
      fullPath: '/api/wa-dashboard/upload'
      preLoaderRoute: typeof ApiWaDashboardUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/session': {
      id: '/api/wa-dashboard/session'
      path: '/api/wa-dashboard/session'
      fullPath: '/api/wa-dashboard/session'
      preLoaderRoute: typeof ApiWaDashboardSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/orders': {
      id: '/api/wa-dashboard/orders'
      path: '/api/wa-dashboard/orders'
      fullPath: '/api/wa-dashboard/orders'
      preLoaderRoute: typeof ApiWaDashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/notifications': {
      id: '/api/wa-dashboard/notifications'
      path: '/api/wa-dashboard/notifications'
      fullPath: '/api/wa-dashboard/notifications'
      preLoaderRoute: typeof ApiWaDashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/logout': {
      id: '/api/wa-dashboard/logout'
      path: '/api/wa-dashboard/logout'
      fullPath: '/api/wa-dashboard/logout'
      preLoaderRoute: typeof ApiWaDashboardLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/login': {
      id: '/api/wa-dashboard/login'
      path: '/api/wa-dashboard/login'
      fullPath: '/api/wa-dashboard/login'
      preLoaderRoute: typeof ApiWaDashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/diagnostics': {
      id: '/api/wa-dashboard/diagnostics'
      path: '/api/wa-dashboard/diagnostics'
      fullPath: '/api/wa-dashboard/diagnostics'
      preLoaderRoute: typeof ApiWaDashboardDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard/catalog': {
      id: '/api/wa-dashboard/catalog'
      path: '/api/wa-dashboard/catalog'
      fullPath: '/api/wa-dashboard/catalog'
      preLoaderRoute: typeof ApiWaDashboardCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/upload': {
      id: '/api/wa-dashboard-2/upload'
      path: '/api/wa-dashboard-2/upload'
      fullPath: '/api/wa-dashboard-2/upload'
      preLoaderRoute: typeof ApiWaDashboard2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/session': {
      id: '/api/wa-dashboard-2/session'
      path: '/api/wa-dashboard-2/session'
      fullPath: '/api/wa-dashboard-2/session'
      preLoaderRoute: typeof ApiWaDashboard2SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/orders': {
      id: '/api/wa-dashboard-2/orders'
      path: '/api/wa-dashboard-2/orders'
      fullPath: '/api/wa-dashboard-2/orders'
      preLoaderRoute: typeof ApiWaDashboard2OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/logout': {
      id: '/api/wa-dashboard-2/logout'
      path: '/api/wa-dashboard-2/logout'
      fullPath: '/api/wa-dashboard-2/logout'
      preLoaderRoute: typeof ApiWaDashboard2LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/login': {
      id: '/api/wa-dashboard-2/login'
      path: '/api/wa-dashboard-2/login'
      fullPath: '/api/wa-dashboard-2/login'
      preLoaderRoute: typeof ApiWaDashboard2LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/diagnostics': {
      id: '/api/wa-dashboard-2/diagnostics'
      path: '/api/wa-dashboard-2/diagnostics'
      fullPath: '/api/wa-dashboard-2/diagnostics'
      preLoaderRoute: typeof ApiWaDashboard2DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-dashboard-2/catalog': {
      id: '/api/wa-dashboard-2/catalog'
      path: '/api/wa-dashboard-2/catalog'
      fullPath: '/api/wa-dashboard-2/catalog'
      preLoaderRoute: typeof ApiWaDashboard2CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/whatsapp-templates': {
      id: '/api/wa-admin/whatsapp-templates'
      path: '/api/wa-admin/whatsapp-templates'
      fullPath: '/api/wa-admin/whatsapp-templates'
      preLoaderRoute: typeof ApiWaAdminWhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/session': {
      id: '/api/wa-admin/session'
      path: '/api/wa-admin/session'
      fullPath: '/api/wa-admin/session'
      preLoaderRoute: typeof ApiWaAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/send-review-message': {
      id: '/api/wa-admin/send-review-message'
      path: '/api/wa-admin/send-review-message'
      fullPath: '/api/wa-admin/send-review-message'
      preLoaderRoute: typeof ApiWaAdminSendReviewMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/review-connections': {
      id: '/api/wa-admin/review-connections'
      path: '/api/wa-admin/review-connections'
      fullPath: '/api/wa-admin/review-connections'
      preLoaderRoute: typeof ApiWaAdminReviewConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/overview': {
      id: '/api/wa-admin/overview'
      path: '/api/wa-admin/overview'
      fullPath: '/api/wa-admin/overview'
      preLoaderRoute: typeof ApiWaAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/message-events': {
      id: '/api/wa-admin/message-events'
      path: '/api/wa-admin/message-events'
      fullPath: '/api/wa-admin/message-events'
      preLoaderRoute: typeof ApiWaAdminMessageEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/logs': {
      id: '/api/wa-admin/logs'
      path: '/api/wa-admin/logs'
      fullPath: '/api/wa-admin/logs'
      preLoaderRoute: typeof ApiWaAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/logout': {
      id: '/api/wa-admin/logout'
      path: '/api/wa-admin/logout'
      fullPath: '/api/wa-admin/logout'
      preLoaderRoute: typeof ApiWaAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/login': {
      id: '/api/wa-admin/login'
      path: '/api/wa-admin/login'
      fullPath: '/api/wa-admin/login'
      preLoaderRoute: typeof ApiWaAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/flow-templates': {
      id: '/api/wa-admin/flow-templates'
      path: '/api/wa-admin/flow-templates'
      fullPath: '/api/wa-admin/flow-templates'
      preLoaderRoute: typeof ApiWaAdminFlowTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-admin/businesses': {
      id: '/api/wa-admin/businesses'
      path: '/api/wa-admin/businesses'
      fullPath: '/api/wa-admin/businesses'
      preLoaderRoute: typeof ApiWaAdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flow-templates/new': {
      id: '/admin/flow-templates/new'
      path: '/new'
      fullPath: '/admin/flow-templates/new'
      preLoaderRoute: typeof AdminFlowTemplatesNewRouteImport
      parentRoute: typeof AdminFlowTemplatesRoute
    }
    '/admin/flow-templates/$templateId': {
      id: '/admin/flow-templates/$templateId'
      path: '/$templateId'
      fullPath: '/admin/flow-templates/$templateId'
      preLoaderRoute: typeof AdminFlowTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminFlowTemplatesRoute
    }
    '/admin/businesses/new': {
      id: '/admin/businesses/new'
      path: '/new'
      fullPath: '/admin/businesses/new'
      preLoaderRoute: typeof AdminBusinessesNewRouteImport
      parentRoute: typeof AdminBusinessesRoute
    }
    '/admin/businesses/$businessId': {
      id: '/admin/businesses/$businessId'
      path: '/$businessId'
      fullPath: '/admin/businesses/$businessId'
      preLoaderRoute: typeof AdminBusinessesBusinessIdRouteImport
      parentRoute: typeof AdminBusinessesRoute
    }
    '/stores/pavone/admin/': {
      id: '/stores/pavone/admin/'
      path: '/'
      fullPath: '/stores/pavone/admin/'
      preLoaderRoute: typeof StoresPavoneAdminIndexRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/product/$slug': {
      id: '/stores/pavone/product/$slug'
      path: '/product/$slug'
      fullPath: '/stores/pavone/product/$slug'
      preLoaderRoute: typeof StoresPavoneProductSlugRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/category/$slug': {
      id: '/stores/pavone/category/$slug'
      path: '/category/$slug'
      fullPath: '/stores/pavone/category/$slug'
      preLoaderRoute: typeof StoresPavoneCategorySlugRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/admin/settings': {
      id: '/stores/pavone/admin/settings'
      path: '/settings'
      fullPath: '/stores/pavone/admin/settings'
      preLoaderRoute: typeof StoresPavoneAdminSettingsRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/products': {
      id: '/stores/pavone/admin/products'
      path: '/products'
      fullPath: '/stores/pavone/admin/products'
      preLoaderRoute: typeof StoresPavoneAdminProductsRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/orders': {
      id: '/stores/pavone/admin/orders'
      path: '/orders'
      fullPath: '/stores/pavone/admin/orders'
      preLoaderRoute: typeof StoresPavoneAdminOrdersRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/login': {
      id: '/stores/pavone/admin/login'
      path: '/login'
      fullPath: '/stores/pavone/admin/login'
      preLoaderRoute: typeof StoresPavoneAdminLoginRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/inspirations': {
      id: '/stores/pavone/admin/inspirations'
      path: '/inspirations'
      fullPath: '/stores/pavone/admin/inspirations'
      preLoaderRoute: typeof StoresPavoneAdminInspirationsRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/categories': {
      id: '/stores/pavone/admin/categories'
      path: '/categories'
      fullPath: '/stores/pavone/admin/categories'
      preLoaderRoute: typeof StoresPavoneAdminCategoriesRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/api/wa-dashboard/orders/$orderId': {
      id: '/api/wa-dashboard/orders/$orderId'
      path: '/$orderId'
      fullPath: '/api/wa-dashboard/orders/$orderId'
      preLoaderRoute: typeof ApiWaDashboardOrdersOrderIdRouteImport
      parentRoute: typeof ApiWaDashboardOrdersRoute
    }
    '/api/wa-dashboard-2/orders/$orderId': {
      id: '/api/wa-dashboard-2/orders/$orderId'
      path: '/$orderId'
      fullPath: '/api/wa-dashboard-2/orders/$orderId'
      preLoaderRoute: typeof ApiWaDashboard2OrdersOrderIdRouteImport
      parentRoute: typeof ApiWaDashboard2OrdersRoute
    }
    '/api/wa-admin/flow-templates/$templateId': {
      id: '/api/wa-admin/flow-templates/$templateId'
      path: '/$templateId'
      fullPath: '/api/wa-admin/flow-templates/$templateId'
      preLoaderRoute: typeof ApiWaAdminFlowTemplatesTemplateIdRouteImport
      parentRoute: typeof ApiWaAdminFlowTemplatesRoute
    }
    '/api/wa-admin/businesses/$businessId': {
      id: '/api/wa-admin/businesses/$businessId'
      path: '/$businessId'
      fullPath: '/api/wa-admin/businesses/$businessId'
      preLoaderRoute: typeof ApiWaAdminBusinessesBusinessIdRouteImport
      parentRoute: typeof ApiWaAdminBusinessesRoute
    }
    '/admin/businesses/$businessId/products': {
      id: '/admin/businesses/$businessId/products'
      path: '/products'
      fullPath: '/admin/businesses/$businessId/products'
      preLoaderRoute: typeof AdminBusinessesBusinessIdProductsRouteImport
      parentRoute: typeof AdminBusinessesBusinessIdRoute
    }
    '/admin/businesses/$businessId/flow-builder': {
      id: '/admin/businesses/$businessId/flow-builder'
      path: '/flow-builder'
      fullPath: '/admin/businesses/$businessId/flow-builder'
      preLoaderRoute: typeof AdminBusinessesBusinessIdFlowBuilderRouteImport
      parentRoute: typeof AdminBusinessesBusinessIdRoute
    }
    '/admin/businesses/$businessId/categories': {
      id: '/admin/businesses/$businessId/categories'
      path: '/categories'
      fullPath: '/admin/businesses/$businessId/categories'
      preLoaderRoute: typeof AdminBusinessesBusinessIdCategoriesRouteImport
      parentRoute: typeof AdminBusinessesBusinessIdRoute
    }
    '/admin/businesses/$businessId/catalog-routes': {
      id: '/admin/businesses/$businessId/catalog-routes'
      path: '/catalog-routes'
      fullPath: '/admin/businesses/$businessId/catalog-routes'
      preLoaderRoute: typeof AdminBusinessesBusinessIdCatalogRoutesRouteImport
      parentRoute: typeof AdminBusinessesBusinessIdRoute
    }
    '/admin/businesses/$businessId/catalog-route-values': {
      id: '/admin/businesses/$businessId/catalog-route-values'
      path: '/catalog-route-values'
      fullPath: '/admin/businesses/$businessId/catalog-route-values'
      preLoaderRoute: typeof AdminBusinessesBusinessIdCatalogRouteValuesRouteImport
      parentRoute: typeof AdminBusinessesBusinessIdRoute
    }
    '/api/wa-admin/businesses/$businessId/flow': {
      id: '/api/wa-admin/businesses/$businessId/flow'
      path: '/flow'
      fullPath: '/api/wa-admin/businesses/$businessId/flow'
      preLoaderRoute: typeof ApiWaAdminBusinessesBusinessIdFlowRouteImport
      parentRoute: typeof ApiWaAdminBusinessesBusinessIdRoute
    }
    '/admin/flow-templates/$templateId/versions/$versionId': {
      id: '/admin/flow-templates/$templateId/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/admin/flow-templates/$templateId/versions/$versionId'
      preLoaderRoute: typeof AdminFlowTemplatesTemplateIdVersionsVersionIdRouteImport
      parentRoute: typeof AdminFlowTemplatesTemplateIdRoute
    }
  }
}

interface AdminBusinessesBusinessIdRouteChildren {
  AdminBusinessesBusinessIdCatalogRouteValuesRoute: typeof AdminBusinessesBusinessIdCatalogRouteValuesRoute
  AdminBusinessesBusinessIdCatalogRoutesRoute: typeof AdminBusinessesBusinessIdCatalogRoutesRoute
  AdminBusinessesBusinessIdCategoriesRoute: typeof AdminBusinessesBusinessIdCategoriesRoute
  AdminBusinessesBusinessIdFlowBuilderRoute: typeof AdminBusinessesBusinessIdFlowBuilderRoute
  AdminBusinessesBusinessIdProductsRoute: typeof AdminBusinessesBusinessIdProductsRoute
}

const AdminBusinessesBusinessIdRouteChildren: AdminBusinessesBusinessIdRouteChildren =
  {
    AdminBusinessesBusinessIdCatalogRouteValuesRoute:
      AdminBusinessesBusinessIdCatalogRouteValuesRoute,
    AdminBusinessesBusinessIdCatalogRoutesRoute:
      AdminBusinessesBusinessIdCatalogRoutesRoute,
    AdminBusinessesBusinessIdCategoriesRoute:
      AdminBusinessesBusinessIdCategoriesRoute,
    AdminBusinessesBusinessIdFlowBuilderRoute:
      AdminBusinessesBusinessIdFlowBuilderRoute,
    AdminBusinessesBusinessIdProductsRoute:
      AdminBusinessesBusinessIdProductsRoute,
  }

const AdminBusinessesBusinessIdRouteWithChildren =
  AdminBusinessesBusinessIdRoute._addFileChildren(
    AdminBusinessesBusinessIdRouteChildren,
  )

interface AdminBusinessesRouteChildren {
  AdminBusinessesBusinessIdRoute: typeof AdminBusinessesBusinessIdRouteWithChildren
  AdminBusinessesNewRoute: typeof AdminBusinessesNewRoute
}

const AdminBusinessesRouteChildren: AdminBusinessesRouteChildren = {
  AdminBusinessesBusinessIdRoute: AdminBusinessesBusinessIdRouteWithChildren,
  AdminBusinessesNewRoute: AdminBusinessesNewRoute,
}

const AdminBusinessesRouteWithChildren = AdminBusinessesRoute._addFileChildren(
  AdminBusinessesRouteChildren,
)

interface AdminFlowTemplatesTemplateIdRouteChildren {
  AdminFlowTemplatesTemplateIdVersionsVersionIdRoute: typeof AdminFlowTemplatesTemplateIdVersionsVersionIdRoute
}

const AdminFlowTemplatesTemplateIdRouteChildren: AdminFlowTemplatesTemplateIdRouteChildren =
  {
    AdminFlowTemplatesTemplateIdVersionsVersionIdRoute:
      AdminFlowTemplatesTemplateIdVersionsVersionIdRoute,
  }

const AdminFlowTemplatesTemplateIdRouteWithChildren =
  AdminFlowTemplatesTemplateIdRoute._addFileChildren(
    AdminFlowTemplatesTemplateIdRouteChildren,
  )

interface AdminFlowTemplatesRouteChildren {
  AdminFlowTemplatesTemplateIdRoute: typeof AdminFlowTemplatesTemplateIdRouteWithChildren
  AdminFlowTemplatesNewRoute: typeof AdminFlowTemplatesNewRoute
}

const AdminFlowTemplatesRouteChildren: AdminFlowTemplatesRouteChildren = {
  AdminFlowTemplatesTemplateIdRoute:
    AdminFlowTemplatesTemplateIdRouteWithChildren,
  AdminFlowTemplatesNewRoute: AdminFlowTemplatesNewRoute,
}

const AdminFlowTemplatesRouteWithChildren =
  AdminFlowTemplatesRoute._addFileChildren(AdminFlowTemplatesRouteChildren)

interface AdminRouteChildren {
  AdminAppReviewDemoRoute: typeof AdminAppReviewDemoRoute
  AdminBusinessesRoute: typeof AdminBusinessesRouteWithChildren
  AdminFlowTemplatesRoute: typeof AdminFlowTemplatesRouteWithChildren
  AdminLogsRoute: typeof AdminLogsRoute
  AdminWhatsappTemplatesRoute: typeof AdminWhatsappTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppReviewDemoRoute: AdminAppReviewDemoRoute,
  AdminBusinessesRoute: AdminBusinessesRouteWithChildren,
  AdminFlowTemplatesRoute: AdminFlowTemplatesRouteWithChildren,
  AdminLogsRoute: AdminLogsRoute,
  AdminWhatsappTemplatesRoute: AdminWhatsappTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardOrdersRouteChildren {
  DashboardOrdersOrderIdRoute: typeof DashboardOrdersOrderIdRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersOrderIdRoute: DashboardOrdersOrderIdRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardDeliveryRoute: typeof DashboardDeliveryRoute
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulatorRoute: typeof DashboardSimulatorRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardDeliveryRoute: DashboardDeliveryRoute,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulatorRoute: DashboardSimulatorRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface Dashboard2OrdersRouteChildren {
  Dashboard2OrdersOrderIdRoute: typeof Dashboard2OrdersOrderIdRoute
}

const Dashboard2OrdersRouteChildren: Dashboard2OrdersRouteChildren = {
  Dashboard2OrdersOrderIdRoute: Dashboard2OrdersOrderIdRoute,
}

const Dashboard2OrdersRouteWithChildren =
  Dashboard2OrdersRoute._addFileChildren(Dashboard2OrdersRouteChildren)

interface Dashboard2RouteChildren {
  Dashboard2CategoriesRoute: typeof Dashboard2CategoriesRoute
  Dashboard2DeliveryRoute: typeof Dashboard2DeliveryRoute
  Dashboard2OrdersRoute: typeof Dashboard2OrdersRouteWithChildren
  Dashboard2ProductsRoute: typeof Dashboard2ProductsRoute
  Dashboard2SettingsRoute: typeof Dashboard2SettingsRoute
  Dashboard2SimulatorRoute: typeof Dashboard2SimulatorRoute
  Dashboard2IndexRoute: typeof Dashboard2IndexRoute
}

const Dashboard2RouteChildren: Dashboard2RouteChildren = {
  Dashboard2CategoriesRoute: Dashboard2CategoriesRoute,
  Dashboard2DeliveryRoute: Dashboard2DeliveryRoute,
  Dashboard2OrdersRoute: Dashboard2OrdersRouteWithChildren,
  Dashboard2ProductsRoute: Dashboard2ProductsRoute,
  Dashboard2SettingsRoute: Dashboard2SettingsRoute,
  Dashboard2SimulatorRoute: Dashboard2SimulatorRoute,
  Dashboard2IndexRoute: Dashboard2IndexRoute,
}

const Dashboard2RouteWithChildren = Dashboard2Route._addFileChildren(
  Dashboard2RouteChildren,
)

interface StoresPavoneAdminRouteChildren {
  StoresPavoneAdminCategoriesRoute: typeof StoresPavoneAdminCategoriesRoute
  StoresPavoneAdminInspirationsRoute: typeof StoresPavoneAdminInspirationsRoute
  StoresPavoneAdminLoginRoute: typeof StoresPavoneAdminLoginRoute
  StoresPavoneAdminOrdersRoute: typeof StoresPavoneAdminOrdersRoute
  StoresPavoneAdminProductsRoute: typeof StoresPavoneAdminProductsRoute
  StoresPavoneAdminSettingsRoute: typeof StoresPavoneAdminSettingsRoute
  StoresPavoneAdminIndexRoute: typeof StoresPavoneAdminIndexRoute
}

const StoresPavoneAdminRouteChildren: StoresPavoneAdminRouteChildren = {
  StoresPavoneAdminCategoriesRoute: StoresPavoneAdminCategoriesRoute,
  StoresPavoneAdminInspirationsRoute: StoresPavoneAdminInspirationsRoute,
  StoresPavoneAdminLoginRoute: StoresPavoneAdminLoginRoute,
  StoresPavoneAdminOrdersRoute: StoresPavoneAdminOrdersRoute,
  StoresPavoneAdminProductsRoute: StoresPavoneAdminProductsRoute,
  StoresPavoneAdminSettingsRoute: StoresPavoneAdminSettingsRoute,
  StoresPavoneAdminIndexRoute: StoresPavoneAdminIndexRoute,
}

const StoresPavoneAdminRouteWithChildren =
  StoresPavoneAdminRoute._addFileChildren(StoresPavoneAdminRouteChildren)

interface StoresPavoneRouteChildren {
  StoresPavoneAdminRoute: typeof StoresPavoneAdminRouteWithChildren
  StoresPavoneShopRoute: typeof StoresPavoneShopRoute
  StoresPavoneWishlistRoute: typeof StoresPavoneWishlistRoute
  StoresPavoneIndexRoute: typeof StoresPavoneIndexRoute
  StoresPavoneCategorySlugRoute: typeof StoresPavoneCategorySlugRoute
  StoresPavoneProductSlugRoute: typeof StoresPavoneProductSlugRoute
}

const StoresPavoneRouteChildren: StoresPavoneRouteChildren = {
  StoresPavoneAdminRoute: StoresPavoneAdminRouteWithChildren,
  StoresPavoneShopRoute: StoresPavoneShopRoute,
  StoresPavoneWishlistRoute: StoresPavoneWishlistRoute,
  StoresPavoneIndexRoute: StoresPavoneIndexRoute,
  StoresPavoneCategorySlugRoute: StoresPavoneCategorySlugRoute,
  StoresPavoneProductSlugRoute: StoresPavoneProductSlugRoute,
}

const StoresPavoneRouteWithChildren = StoresPavoneRoute._addFileChildren(
  StoresPavoneRouteChildren,
)

interface StoresRouteChildren {
  StoresPavoneRoute: typeof StoresPavoneRouteWithChildren
  StoresIndexRoute: typeof StoresIndexRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresPavoneRoute: StoresPavoneRouteWithChildren,
  StoresIndexRoute: StoresIndexRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

interface ApiWaAdminBusinessesBusinessIdRouteChildren {
  ApiWaAdminBusinessesBusinessIdFlowRoute: typeof ApiWaAdminBusinessesBusinessIdFlowRoute
}

const ApiWaAdminBusinessesBusinessIdRouteChildren: ApiWaAdminBusinessesBusinessIdRouteChildren =
  {
    ApiWaAdminBusinessesBusinessIdFlowRoute:
      ApiWaAdminBusinessesBusinessIdFlowRoute,
  }

const ApiWaAdminBusinessesBusinessIdRouteWithChildren =
  ApiWaAdminBusinessesBusinessIdRoute._addFileChildren(
    ApiWaAdminBusinessesBusinessIdRouteChildren,
  )

interface ApiWaAdminBusinessesRouteChildren {
  ApiWaAdminBusinessesBusinessIdRoute: typeof ApiWaAdminBusinessesBusinessIdRouteWithChildren
}

const ApiWaAdminBusinessesRouteChildren: ApiWaAdminBusinessesRouteChildren = {
  ApiWaAdminBusinessesBusinessIdRoute:
    ApiWaAdminBusinessesBusinessIdRouteWithChildren,
}

const ApiWaAdminBusinessesRouteWithChildren =
  ApiWaAdminBusinessesRoute._addFileChildren(ApiWaAdminBusinessesRouteChildren)

interface ApiWaAdminFlowTemplatesRouteChildren {
  ApiWaAdminFlowTemplatesTemplateIdRoute: typeof ApiWaAdminFlowTemplatesTemplateIdRoute
}

const ApiWaAdminFlowTemplatesRouteChildren: ApiWaAdminFlowTemplatesRouteChildren =
  {
    ApiWaAdminFlowTemplatesTemplateIdRoute:
      ApiWaAdminFlowTemplatesTemplateIdRoute,
  }

const ApiWaAdminFlowTemplatesRouteWithChildren =
  ApiWaAdminFlowTemplatesRoute._addFileChildren(
    ApiWaAdminFlowTemplatesRouteChildren,
  )

interface ApiWaDashboard2OrdersRouteChildren {
  ApiWaDashboard2OrdersOrderIdRoute: typeof ApiWaDashboard2OrdersOrderIdRoute
}

const ApiWaDashboard2OrdersRouteChildren: ApiWaDashboard2OrdersRouteChildren = {
  ApiWaDashboard2OrdersOrderIdRoute: ApiWaDashboard2OrdersOrderIdRoute,
}

const ApiWaDashboard2OrdersRouteWithChildren =
  ApiWaDashboard2OrdersRoute._addFileChildren(
    ApiWaDashboard2OrdersRouteChildren,
  )

interface ApiWaDashboardOrdersRouteChildren {
  ApiWaDashboardOrdersOrderIdRoute: typeof ApiWaDashboardOrdersOrderIdRoute
}

const ApiWaDashboardOrdersRouteChildren: ApiWaDashboardOrdersRouteChildren = {
  ApiWaDashboardOrdersOrderIdRoute: ApiWaDashboardOrdersOrderIdRoute,
}

const ApiWaDashboardOrdersRouteWithChildren =
  ApiWaDashboardOrdersRoute._addFileChildren(ApiWaDashboardOrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  Dashboard2Route: Dashboard2RouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  LogsWABotRoute: LogsWABotRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SpreadsheetRoute: SpreadsheetRoute,
  StoresRoute: StoresRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  MenusMarleysRoute: MenusMarleysRoute,
  QuotationsKhadamatiRoute: QuotationsKhadamatiRoute,
  WorkDataInsightsRoute: WorkDataInsightsRoute,
  WorkDetailingLabRoute: WorkDetailingLabRoute,
  WorkKoubarGroupRoute: WorkKoubarGroupRoute,
  WorkSnapgoRoute: WorkSnapgoRoute,
  WorkTijaratiProRoute: WorkTijaratiProRoute,
  WorkUno400Route: WorkUno400Route,
  ApiWaAdminBusinessesRoute: ApiWaAdminBusinessesRouteWithChildren,
  ApiWaAdminFlowTemplatesRoute: ApiWaAdminFlowTemplatesRouteWithChildren,
  ApiWaAdminLoginRoute: ApiWaAdminLoginRoute,
  ApiWaAdminLogoutRoute: ApiWaAdminLogoutRoute,
  ApiWaAdminLogsRoute: ApiWaAdminLogsRoute,
  ApiWaAdminMessageEventsRoute: ApiWaAdminMessageEventsRoute,
  ApiWaAdminOverviewRoute: ApiWaAdminOverviewRoute,
  ApiWaAdminReviewConnectionsRoute: ApiWaAdminReviewConnectionsRoute,
  ApiWaAdminSendReviewMessageRoute: ApiWaAdminSendReviewMessageRoute,
  ApiWaAdminSessionRoute: ApiWaAdminSessionRoute,
  ApiWaAdminWhatsappTemplatesRoute: ApiWaAdminWhatsappTemplatesRoute,
  ApiWaDashboard2CatalogRoute: ApiWaDashboard2CatalogRoute,
  ApiWaDashboard2DiagnosticsRoute: ApiWaDashboard2DiagnosticsRoute,
  ApiWaDashboard2LoginRoute: ApiWaDashboard2LoginRoute,
  ApiWaDashboard2LogoutRoute: ApiWaDashboard2LogoutRoute,
  ApiWaDashboard2OrdersRoute: ApiWaDashboard2OrdersRouteWithChildren,
  ApiWaDashboard2SessionRoute: ApiWaDashboard2SessionRoute,
  ApiWaDashboard2UploadRoute: ApiWaDashboard2UploadRoute,
  ApiWaDashboardCatalogRoute: ApiWaDashboardCatalogRoute,
  ApiWaDashboardDiagnosticsRoute: ApiWaDashboardDiagnosticsRoute,
  ApiWaDashboardLoginRoute: ApiWaDashboardLoginRoute,
  ApiWaDashboardLogoutRoute: ApiWaDashboardLogoutRoute,
  ApiWaDashboardNotificationsRoute: ApiWaDashboardNotificationsRoute,
  ApiWaDashboardOrdersRoute: ApiWaDashboardOrdersRouteWithChildren,
  ApiWaDashboardSessionRoute: ApiWaDashboardSessionRoute,
  ApiWaDashboardUploadRoute: ApiWaDashboardUploadRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiWhatsappWebhook2Route: ApiWhatsappWebhook2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
