/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SpreadsheetRouteImport } from './routes/spreadsheet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as WorkUno400RouteImport } from './routes/work/uno400'
import { Route as WorkTijaratiProRouteImport } from './routes/work/tijarati-pro'
import { Route as WorkSnapgoRouteImport } from './routes/work/snapgo'
import { Route as WorkKoubarGroupRouteImport } from './routes/work/koubar-group'
import { Route as WorkDetailingLabRouteImport } from './routes/work/detailing-lab'
import { Route as WorkDataInsightsRouteImport } from './routes/work/data-insights'
import { Route as StoresPavoneRouteImport } from './routes/stores/pavone'
import { Route as MenusMarleysRouteImport } from './routes/menus/marleys'
import { Route as DashboardSimulatorRouteImport } from './routes/dashboard.simulator'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as StoresPavoneIndexRouteImport } from './routes/stores/pavone.index'
import { Route as StoresPavoneWishlistRouteImport } from './routes/stores/pavone.wishlist'
import { Route as StoresPavoneShopRouteImport } from './routes/stores/pavone.shop'
import { Route as StoresPavoneAdminRouteImport } from './routes/stores/pavone.admin'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as StoresPavoneAdminIndexRouteImport } from './routes/stores/pavone.admin.index'
import { Route as StoresPavoneProductSlugRouteImport } from './routes/stores/pavone.product.$slug'
import { Route as StoresPavoneCategorySlugRouteImport } from './routes/stores/pavone.category.$slug'
import { Route as StoresPavoneAdminSettingsRouteImport } from './routes/stores/pavone.admin.settings'
import { Route as StoresPavoneAdminProductsRouteImport } from './routes/stores/pavone.admin.products'
import { Route as StoresPavoneAdminOrdersRouteImport } from './routes/stores/pavone.admin.orders'
import { Route as StoresPavoneAdminLoginRouteImport } from './routes/stores/pavone.admin.login'
import { Route as StoresPavoneAdminInspirationsRouteImport } from './routes/stores/pavone.admin.inspirations'
import { Route as StoresPavoneAdminCategoriesRouteImport } from './routes/stores/pavone.admin.categories'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsheetRoute = SpreadsheetRouteImport.update({
  id: '/spreadsheet',
  path: '/spreadsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WorkUno400Route = WorkUno400RouteImport.update({
  id: '/work/uno400',
  path: '/work/uno400',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTijaratiProRoute = WorkTijaratiProRouteImport.update({
  id: '/work/tijarati-pro',
  path: '/work/tijarati-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSnapgoRoute = WorkSnapgoRouteImport.update({
  id: '/work/snapgo',
  path: '/work/snapgo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkKoubarGroupRoute = WorkKoubarGroupRouteImport.update({
  id: '/work/koubar-group',
  path: '/work/koubar-group',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDetailingLabRoute = WorkDetailingLabRouteImport.update({
  id: '/work/detailing-lab',
  path: '/work/detailing-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDataInsightsRoute = WorkDataInsightsRouteImport.update({
  id: '/work/data-insights',
  path: '/work/data-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresPavoneRoute = StoresPavoneRouteImport.update({
  id: '/pavone',
  path: '/pavone',
  getParentRoute: () => StoresRoute,
} as any)
const MenusMarleysRoute = MenusMarleysRouteImport.update({
  id: '/menus/marleys',
  path: '/menus/marleys',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSimulatorRoute = DashboardSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const StoresPavoneIndexRoute = StoresPavoneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneWishlistRoute = StoresPavoneWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneShopRoute = StoresPavoneShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneAdminRoute = StoresPavoneAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresPavoneAdminIndexRoute = StoresPavoneAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresPavoneAdminRoute,
} as any)
const StoresPavoneProductSlugRoute = StoresPavoneProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => StoresPavoneRoute,
} as any)
const StoresPavoneCategorySlugRoute =
  StoresPavoneCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => StoresPavoneRoute,
  } as any)
const StoresPavoneAdminSettingsRoute =
  StoresPavoneAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const StoresPavoneAdminProductsRoute =
  StoresPavoneAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const StoresPavoneAdminOrdersRoute = StoresPavoneAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoresPavoneAdminRoute,
} as any)
const StoresPavoneAdminLoginRoute = StoresPavoneAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StoresPavoneAdminRoute,
} as any)
const StoresPavoneAdminInspirationsRoute =
  StoresPavoneAdminInspirationsRouteImport.update({
    id: '/inspirations',
    path: '/inspirations',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)
const StoresPavoneAdminCategoriesRoute =
  StoresPavoneAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => StoresPavoneAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/spreadsheet': typeof SpreadsheetRoute
  '/stores': typeof StoresRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/stores/pavone': typeof StoresPavoneRouteWithChildren
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/koubar-group': typeof WorkKoubarGroupRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
  '/work/uno400': typeof WorkUno400Route
  '/dashboard/': typeof DashboardIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/stores/pavone/admin': typeof StoresPavoneAdminRouteWithChildren
  '/stores/pavone/shop': typeof StoresPavoneShopRoute
  '/stores/pavone/wishlist': typeof StoresPavoneWishlistRoute
  '/stores/pavone/': typeof StoresPavoneIndexRoute
  '/stores/pavone/admin/categories': typeof StoresPavoneAdminCategoriesRoute
  '/stores/pavone/admin/inspirations': typeof StoresPavoneAdminInspirationsRoute
  '/stores/pavone/admin/login': typeof StoresPavoneAdminLoginRoute
  '/stores/pavone/admin/orders': typeof StoresPavoneAdminOrdersRoute
  '/stores/pavone/admin/products': typeof StoresPavoneAdminProductsRoute
  '/stores/pavone/admin/settings': typeof StoresPavoneAdminSettingsRoute
  '/stores/pavone/category/$slug': typeof StoresPavoneCategorySlugRoute
  '/stores/pavone/product/$slug': typeof StoresPavoneProductSlugRoute
  '/stores/pavone/admin/': typeof StoresPavoneAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/spreadsheet': typeof SpreadsheetRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/koubar-group': typeof WorkKoubarGroupRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
  '/work/uno400': typeof WorkUno400Route
  '/dashboard': typeof DashboardIndexRoute
  '/stores': typeof StoresIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/stores/pavone/shop': typeof StoresPavoneShopRoute
  '/stores/pavone/wishlist': typeof StoresPavoneWishlistRoute
  '/stores/pavone': typeof StoresPavoneIndexRoute
  '/stores/pavone/admin/categories': typeof StoresPavoneAdminCategoriesRoute
  '/stores/pavone/admin/inspirations': typeof StoresPavoneAdminInspirationsRoute
  '/stores/pavone/admin/login': typeof StoresPavoneAdminLoginRoute
  '/stores/pavone/admin/orders': typeof StoresPavoneAdminOrdersRoute
  '/stores/pavone/admin/products': typeof StoresPavoneAdminProductsRoute
  '/stores/pavone/admin/settings': typeof StoresPavoneAdminSettingsRoute
  '/stores/pavone/category/$slug': typeof StoresPavoneCategorySlugRoute
  '/stores/pavone/product/$slug': typeof StoresPavoneProductSlugRoute
  '/stores/pavone/admin': typeof StoresPavoneAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/spreadsheet': typeof SpreadsheetRoute
  '/stores': typeof StoresRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/stores/pavone': typeof StoresPavoneRouteWithChildren
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/koubar-group': typeof WorkKoubarGroupRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
  '/work/uno400': typeof WorkUno400Route
  '/dashboard/': typeof DashboardIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/stores/pavone/admin': typeof StoresPavoneAdminRouteWithChildren
  '/stores/pavone/shop': typeof StoresPavoneShopRoute
  '/stores/pavone/wishlist': typeof StoresPavoneWishlistRoute
  '/stores/pavone/': typeof StoresPavoneIndexRoute
  '/stores/pavone/admin/categories': typeof StoresPavoneAdminCategoriesRoute
  '/stores/pavone/admin/inspirations': typeof StoresPavoneAdminInspirationsRoute
  '/stores/pavone/admin/login': typeof StoresPavoneAdminLoginRoute
  '/stores/pavone/admin/orders': typeof StoresPavoneAdminOrdersRoute
  '/stores/pavone/admin/products': typeof StoresPavoneAdminProductsRoute
  '/stores/pavone/admin/settings': typeof StoresPavoneAdminSettingsRoute
  '/stores/pavone/category/$slug': typeof StoresPavoneCategorySlugRoute
  '/stores/pavone/product/$slug': typeof StoresPavoneProductSlugRoute
  '/stores/pavone/admin/': typeof StoresPavoneAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/spreadsheet'
    | '/stores'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/simulator'
    | '/menus/marleys'
    | '/stores/pavone'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/koubar-group'
    | '/work/snapgo'
    | '/work/tijarati-pro'
    | '/work/uno400'
    | '/dashboard/'
    | '/stores/'
    | '/api/whatsapp/webhook'
    | '/stores/pavone/admin'
    | '/stores/pavone/shop'
    | '/stores/pavone/wishlist'
    | '/stores/pavone/'
    | '/stores/pavone/admin/categories'
    | '/stores/pavone/admin/inspirations'
    | '/stores/pavone/admin/login'
    | '/stores/pavone/admin/orders'
    | '/stores/pavone/admin/products'
    | '/stores/pavone/admin/settings'
    | '/stores/pavone/category/$slug'
    | '/stores/pavone/product/$slug'
    | '/stores/pavone/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/spreadsheet'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/simulator'
    | '/menus/marleys'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/koubar-group'
    | '/work/snapgo'
    | '/work/tijarati-pro'
    | '/work/uno400'
    | '/dashboard'
    | '/stores'
    | '/api/whatsapp/webhook'
    | '/stores/pavone/shop'
    | '/stores/pavone/wishlist'
    | '/stores/pavone'
    | '/stores/pavone/admin/categories'
    | '/stores/pavone/admin/inspirations'
    | '/stores/pavone/admin/login'
    | '/stores/pavone/admin/orders'
    | '/stores/pavone/admin/products'
    | '/stores/pavone/admin/settings'
    | '/stores/pavone/category/$slug'
    | '/stores/pavone/product/$slug'
    | '/stores/pavone/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/spreadsheet'
    | '/stores'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/simulator'
    | '/menus/marleys'
    | '/stores/pavone'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/koubar-group'
    | '/work/snapgo'
    | '/work/tijarati-pro'
    | '/work/uno400'
    | '/dashboard/'
    | '/stores/'
    | '/api/whatsapp/webhook'
    | '/stores/pavone/admin'
    | '/stores/pavone/shop'
    | '/stores/pavone/wishlist'
    | '/stores/pavone/'
    | '/stores/pavone/admin/categories'
    | '/stores/pavone/admin/inspirations'
    | '/stores/pavone/admin/login'
    | '/stores/pavone/admin/orders'
    | '/stores/pavone/admin/products'
    | '/stores/pavone/admin/settings'
    | '/stores/pavone/category/$slug'
    | '/stores/pavone/product/$slug'
    | '/stores/pavone/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SpreadsheetRoute: typeof SpreadsheetRoute
  StoresRoute: typeof StoresRouteWithChildren
  MenusMarleysRoute: typeof MenusMarleysRoute
  WorkDataInsightsRoute: typeof WorkDataInsightsRoute
  WorkDetailingLabRoute: typeof WorkDetailingLabRoute
  WorkKoubarGroupRoute: typeof WorkKoubarGroupRoute
  WorkSnapgoRoute: typeof WorkSnapgoRoute
  WorkTijaratiProRoute: typeof WorkTijaratiProRoute
  WorkUno400Route: typeof WorkUno400Route
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreadsheet': {
      id: '/spreadsheet'
      path: '/spreadsheet'
      fullPath: '/spreadsheet'
      preLoaderRoute: typeof SpreadsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof StoresRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/work/uno400': {
      id: '/work/uno400'
      path: '/work/uno400'
      fullPath: '/work/uno400'
      preLoaderRoute: typeof WorkUno400RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/tijarati-pro': {
      id: '/work/tijarati-pro'
      path: '/work/tijarati-pro'
      fullPath: '/work/tijarati-pro'
      preLoaderRoute: typeof WorkTijaratiProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/snapgo': {
      id: '/work/snapgo'
      path: '/work/snapgo'
      fullPath: '/work/snapgo'
      preLoaderRoute: typeof WorkSnapgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/koubar-group': {
      id: '/work/koubar-group'
      path: '/work/koubar-group'
      fullPath: '/work/koubar-group'
      preLoaderRoute: typeof WorkKoubarGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/detailing-lab': {
      id: '/work/detailing-lab'
      path: '/work/detailing-lab'
      fullPath: '/work/detailing-lab'
      preLoaderRoute: typeof WorkDetailingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/data-insights': {
      id: '/work/data-insights'
      path: '/work/data-insights'
      fullPath: '/work/data-insights'
      preLoaderRoute: typeof WorkDataInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/pavone': {
      id: '/stores/pavone'
      path: '/pavone'
      fullPath: '/stores/pavone'
      preLoaderRoute: typeof StoresPavoneRouteImport
      parentRoute: typeof StoresRoute
    }
    '/menus/marleys': {
      id: '/menus/marleys'
      path: '/menus/marleys'
      fullPath: '/menus/marleys'
      preLoaderRoute: typeof MenusMarleysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/simulator': {
      id: '/dashboard/simulator'
      path: '/simulator'
      fullPath: '/dashboard/simulator'
      preLoaderRoute: typeof DashboardSimulatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/stores/pavone/': {
      id: '/stores/pavone/'
      path: '/'
      fullPath: '/stores/pavone/'
      preLoaderRoute: typeof StoresPavoneIndexRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/wishlist': {
      id: '/stores/pavone/wishlist'
      path: '/wishlist'
      fullPath: '/stores/pavone/wishlist'
      preLoaderRoute: typeof StoresPavoneWishlistRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/shop': {
      id: '/stores/pavone/shop'
      path: '/shop'
      fullPath: '/stores/pavone/shop'
      preLoaderRoute: typeof StoresPavoneShopRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/admin': {
      id: '/stores/pavone/admin'
      path: '/admin'
      fullPath: '/stores/pavone/admin'
      preLoaderRoute: typeof StoresPavoneAdminRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/pavone/admin/': {
      id: '/stores/pavone/admin/'
      path: '/'
      fullPath: '/stores/pavone/admin/'
      preLoaderRoute: typeof StoresPavoneAdminIndexRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/product/$slug': {
      id: '/stores/pavone/product/$slug'
      path: '/product/$slug'
      fullPath: '/stores/pavone/product/$slug'
      preLoaderRoute: typeof StoresPavoneProductSlugRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/category/$slug': {
      id: '/stores/pavone/category/$slug'
      path: '/category/$slug'
      fullPath: '/stores/pavone/category/$slug'
      preLoaderRoute: typeof StoresPavoneCategorySlugRouteImport
      parentRoute: typeof StoresPavoneRoute
    }
    '/stores/pavone/admin/settings': {
      id: '/stores/pavone/admin/settings'
      path: '/settings'
      fullPath: '/stores/pavone/admin/settings'
      preLoaderRoute: typeof StoresPavoneAdminSettingsRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/products': {
      id: '/stores/pavone/admin/products'
      path: '/products'
      fullPath: '/stores/pavone/admin/products'
      preLoaderRoute: typeof StoresPavoneAdminProductsRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/orders': {
      id: '/stores/pavone/admin/orders'
      path: '/orders'
      fullPath: '/stores/pavone/admin/orders'
      preLoaderRoute: typeof StoresPavoneAdminOrdersRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/login': {
      id: '/stores/pavone/admin/login'
      path: '/login'
      fullPath: '/stores/pavone/admin/login'
      preLoaderRoute: typeof StoresPavoneAdminLoginRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/inspirations': {
      id: '/stores/pavone/admin/inspirations'
      path: '/inspirations'
      fullPath: '/stores/pavone/admin/inspirations'
      preLoaderRoute: typeof StoresPavoneAdminInspirationsRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
    '/stores/pavone/admin/categories': {
      id: '/stores/pavone/admin/categories'
      path: '/categories'
      fullPath: '/stores/pavone/admin/categories'
      preLoaderRoute: typeof StoresPavoneAdminCategoriesRouteImport
      parentRoute: typeof StoresPavoneAdminRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSimulatorRoute: typeof DashboardSimulatorRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSimulatorRoute: DashboardSimulatorRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StoresPavoneAdminRouteChildren {
  StoresPavoneAdminCategoriesRoute: typeof StoresPavoneAdminCategoriesRoute
  StoresPavoneAdminInspirationsRoute: typeof StoresPavoneAdminInspirationsRoute
  StoresPavoneAdminLoginRoute: typeof StoresPavoneAdminLoginRoute
  StoresPavoneAdminOrdersRoute: typeof StoresPavoneAdminOrdersRoute
  StoresPavoneAdminProductsRoute: typeof StoresPavoneAdminProductsRoute
  StoresPavoneAdminSettingsRoute: typeof StoresPavoneAdminSettingsRoute
  StoresPavoneAdminIndexRoute: typeof StoresPavoneAdminIndexRoute
}

const StoresPavoneAdminRouteChildren: StoresPavoneAdminRouteChildren = {
  StoresPavoneAdminCategoriesRoute: StoresPavoneAdminCategoriesRoute,
  StoresPavoneAdminInspirationsRoute: StoresPavoneAdminInspirationsRoute,
  StoresPavoneAdminLoginRoute: StoresPavoneAdminLoginRoute,
  StoresPavoneAdminOrdersRoute: StoresPavoneAdminOrdersRoute,
  StoresPavoneAdminProductsRoute: StoresPavoneAdminProductsRoute,
  StoresPavoneAdminSettingsRoute: StoresPavoneAdminSettingsRoute,
  StoresPavoneAdminIndexRoute: StoresPavoneAdminIndexRoute,
}

const StoresPavoneAdminRouteWithChildren =
  StoresPavoneAdminRoute._addFileChildren(StoresPavoneAdminRouteChildren)

interface StoresPavoneRouteChildren {
  StoresPavoneAdminRoute: typeof StoresPavoneAdminRouteWithChildren
  StoresPavoneShopRoute: typeof StoresPavoneShopRoute
  StoresPavoneWishlistRoute: typeof StoresPavoneWishlistRoute
  StoresPavoneIndexRoute: typeof StoresPavoneIndexRoute
  StoresPavoneCategorySlugRoute: typeof StoresPavoneCategorySlugRoute
  StoresPavoneProductSlugRoute: typeof StoresPavoneProductSlugRoute
}

const StoresPavoneRouteChildren: StoresPavoneRouteChildren = {
  StoresPavoneAdminRoute: StoresPavoneAdminRouteWithChildren,
  StoresPavoneShopRoute: StoresPavoneShopRoute,
  StoresPavoneWishlistRoute: StoresPavoneWishlistRoute,
  StoresPavoneIndexRoute: StoresPavoneIndexRoute,
  StoresPavoneCategorySlugRoute: StoresPavoneCategorySlugRoute,
  StoresPavoneProductSlugRoute: StoresPavoneProductSlugRoute,
}

const StoresPavoneRouteWithChildren = StoresPavoneRoute._addFileChildren(
  StoresPavoneRouteChildren,
)

interface StoresRouteChildren {
  StoresPavoneRoute: typeof StoresPavoneRouteWithChildren
  StoresIndexRoute: typeof StoresIndexRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresPavoneRoute: StoresPavoneRouteWithChildren,
  StoresIndexRoute: StoresIndexRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SpreadsheetRoute: SpreadsheetRoute,
  StoresRoute: StoresRouteWithChildren,
  MenusMarleysRoute: MenusMarleysRoute,
  WorkDataInsightsRoute: WorkDataInsightsRoute,
  WorkDetailingLabRoute: WorkDetailingLabRoute,
  WorkKoubarGroupRoute: WorkKoubarGroupRoute,
  WorkSnapgoRoute: WorkSnapgoRoute,
  WorkTijaratiProRoute: WorkTijaratiProRoute,
  WorkUno400Route: WorkUno400Route,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
